[package]
name = "snap-n-pull"
version = { workspace = true }
edition = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "-O4"]

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib", "rlib"]

# Define your features
[features]
default = ["wasm", "common", "keys", "req", "wallet"]
wasm = ["wasm-bindgen"]          # Enables WASM bindings generation
common = []         # Enables SnapCommonError
keys = []           # Enables SnapKeyError
req = []            # Enables SnapReqError
wallet = [] # Enables wallet features and pulls in its dependency

# Dependencies (marked as optional so they are only pulled with their feature)
[dependencies]
cosmos-sdk-proto  = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
group  = { workspace = true }
hex = "0.4.3"
js-sys = "0.3.82"
prost  = { workspace = true }
rand = "0.8"
secp256k1 = { workspace = true, features = ["rand"] }
serde  = { workspace = true }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0"
sha3 = "0.10"
thiserror = { version = "1.0" }
tokio = { version = "1.0", features = ["rt", "macros"] }
tonic = { workspace = true }
tonic-web-wasm-client = "0.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-web = { version = "0.1.3" }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = "0.4.43"
wasm-bindgen-rayon = { version = "1.3" } # Update to higher version cause playwright test in chtomium fail
zk-cosmwasm = { workspace = true }
zk-headstash = { path = "../../../headstash/circuit", features = ["rpc"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
