//! Proto-based code generation for ict-rs.
//!
//! Reads `.proto` files via prost-build, extracts Msg and Query service
//! definitions, and generates async extension traits that compose CLI commands
//! under the hood.
//!
//! # Usage in `build.rs`
//!
//! ```ignore
//! // build.rs
//! fn main() {
//!     ict_rs_codegen::CodegenBuilder::new()
//!         .proto_includes(&["proto", "third_party/proto"])
//!         .proto_files(&[
//!             "proto/osmosis/tokenfactory/v1beta1/tx.proto",
//!             "proto/osmosis/tokenfactory/v1beta1/query.proto",
//!         ])
//!         .generate()
//!         .expect("ict-rs codegen failed");
//! }
//! ```
//!
//! Then in your crate:
//!
//! ```ignore
//! include!(concat!(env!("OUT_DIR"), "/tokenfactory.rs"));
//! ```

pub mod cli_mapping;
pub mod msg_codegen;
pub mod naming;
pub mod proto_parser;
pub mod query_codegen;
pub mod text_parser;

use std::path::{Path, PathBuf};

/// Builder for configuring and running proto → trait codegen.
pub struct CodegenBuilder {
    proto_includes: Vec<PathBuf>,
    proto_files: Vec<PathBuf>,
    out_dir: Option<PathBuf>,
}

impl CodegenBuilder {
    /// Create a new builder with no proto files configured.
    pub fn new() -> Self {
        Self {
            proto_includes: Vec::new(),
            proto_files: Vec::new(),
            out_dir: None,
        }
    }

    /// Add directories to search for proto imports.
    pub fn proto_includes(mut self, paths: &[impl AsRef<Path>]) -> Self {
        self.proto_includes
            .extend(paths.iter().map(|p| p.as_ref().to_path_buf()));
        self
    }

    /// Add `.proto` files to generate from.
    pub fn proto_files(mut self, paths: &[impl AsRef<Path>]) -> Self {
        self.proto_files
            .extend(paths.iter().map(|p| p.as_ref().to_path_buf()));
        self
    }

    /// Override the output directory (defaults to `OUT_DIR` env var).
    pub fn out_dir(mut self, path: impl AsRef<Path>) -> Self {
        self.out_dir = Some(path.as_ref().to_path_buf());
        self
    }

    /// Run code generation.
    ///
    /// 1. Compiles protos via prost-build to get `FileDescriptorSet`
    /// 2. Extracts Msg/Query services
    /// 3. Generates `.rs` trait files in `OUT_DIR`
    pub fn generate(self) -> Result<(), Box<dyn std::error::Error>> {
        let out_dir = self
            .out_dir
            .or_else(|| std::env::var("OUT_DIR").ok().map(PathBuf::from))
            .ok_or("OUT_DIR not set and no out_dir configured")?;

        // Use prost-build to compile protos and get file descriptor set
        let descriptor_path = out_dir.join("proto_descriptor.bin");

        let mut prost_config = prost_build::Config::new();
        prost_config.file_descriptor_set_path(&descriptor_path);
        // We don't need prost to generate Rust structs — we just want the descriptors
        prost_config.out_dir(&out_dir);

        prost_config.compile_protos(
            &self.proto_files,
            &self.proto_includes,
        )?;

        // Read back the file descriptor set
        let descriptor_bytes = std::fs::read(&descriptor_path)?;
        let fds = <prost_types::FileDescriptorSet as prost::Message>::decode(
            descriptor_bytes.as_slice(),
        )
        .map_err(|e| format!("failed to decode FileDescriptorSet: {e}"))?;

        // Extract services
        let services = proto_parser::extract_services(&fds);

        // Group by module and generate
        use std::collections::HashMap;
        let mut by_module: HashMap<String, Vec<&proto_parser::ParsedService>> = HashMap::new();
        for svc in &services {
            let module = naming::module_from_package(&svc.package);
            by_module.entry(module).or_default().push(svc);
        }

        for (module, svcs) in &by_module {
            let mut code = String::new();
            code.push_str("// Auto-generated by ict-rs-codegen. Do not edit.\n\n");

            for svc in svcs {
                match svc.name.as_str() {
                    "Msg" => {
                        // CodegenBuilder is for downstream crates → use ict_rs::
                        code.push_str(&msg_codegen::generate_msg_trait_with_path(svc, "ict_rs"));
                        code.push('\n');
                    }
                    "Query" => {
                        code.push_str(&query_codegen::generate_query_trait_with_path(svc, "ict_rs"));
                        code.push('\n');
                    }
                    _ => {}
                }
            }

            let output_path = out_dir.join(format!("{module}.rs"));
            std::fs::write(&output_path, code)?;
        }

        Ok(())
    }
}

impl Default for CodegenBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Builder for text-based proto codegen (no `protoc` required).
///
/// Reads `.proto` files as text and generates the same trait files
/// as `CodegenBuilder`, but without requiring `protoc` to be installed.
pub struct TextCodegenBuilder {
    proto_dirs: Vec<PathBuf>,
    out_dir: Option<PathBuf>,
}

impl TextCodegenBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self {
            proto_dirs: Vec::new(),
            out_dir: None,
        }
    }

    /// Add directories to search recursively for `.proto` files.
    pub fn proto_dirs(mut self, paths: &[impl AsRef<Path>]) -> Self {
        self.proto_dirs
            .extend(paths.iter().map(|p| p.as_ref().to_path_buf()));
        self
    }

    /// Set the output directory for generated files.
    pub fn out_dir(mut self, path: impl AsRef<Path>) -> Self {
        self.out_dir = Some(path.as_ref().to_path_buf());
        self
    }

    /// Run code generation.
    ///
    /// 1. Discovers `tx.proto` and `query.proto` files recursively
    /// 2. Parses them with the text parser
    /// 3. Generates `.rs` trait files in the output directory
    /// 4. Generates a `mod.rs` with feature-gated re-exports
    pub fn generate(self) -> Result<Vec<String>, Box<dyn std::error::Error>> {
        let out_dir = self
            .out_dir
            .ok_or("out_dir is required for TextCodegenBuilder")?;

        std::fs::create_dir_all(&out_dir)?;

        // Discover proto files
        let mut proto_files = Vec::new();
        for dir in &self.proto_dirs {
            discover_proto_files(dir, &mut proto_files)?;
        }

        // Parse all proto files and collect services
        let mut all_services = Vec::new();
        for path in &proto_files {
            let content = std::fs::read_to_string(path)?;
            let services = text_parser::parse_proto_text(&content);
            all_services.extend(services);
        }

        // Group by module
        use std::collections::HashMap;
        let mut by_module: HashMap<String, Vec<&proto_parser::ParsedService>> = HashMap::new();
        for svc in &all_services {
            let module = naming::module_from_package(&svc.package);
            by_module.entry(module).or_default().push(svc);
        }

        let mut modules: Vec<String> = by_module.keys().cloned().collect();
        modules.sort();

        // Generate per-module files
        for (module, svcs) in &by_module {
            let mut code = String::new();
            code.push_str("// Auto-generated by ict-rs-codegen. Do not edit.\n\n");

            for svc in svcs {
                match svc.name.as_str() {
                    "Msg" => {
                        code.push_str(&msg_codegen::generate_msg_trait(svc));
                        code.push('\n');
                    }
                    "Query" => {
                        code.push_str(&query_codegen::generate_query_trait(svc));
                        code.push('\n');
                    }
                    _ => {}
                }
            }

            let output_path = out_dir.join(format!("{module}.rs"));
            std::fs::write(&output_path, code)?;
        }

        // Generate mod.rs with feature-gated re-exports
        let mut mod_code = String::new();
        mod_code.push_str("// Auto-generated by ict-rs-codegen. Do not edit.\n\n");

        for module in &modules {
            mod_code.push_str(&format!(
                "#[cfg(feature = \"{module}\")]\npub mod {module};\n"
            ));
        }

        std::fs::write(out_dir.join("mod.rs"), mod_code)?;

        Ok(modules)
    }
}

impl Default for TextCodegenBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Recursively discover `tx.proto` and `query.proto` files.
fn discover_proto_files(
    dir: &Path,
    out: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            discover_proto_files(&path, out)?;
        } else if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            if name == "tx.proto" || name == "query.proto" {
                out.push(path);
            }
        }
    }
    Ok(()
    )
}

