//! Generate execute (Msg) trait code from parsed service definitions.
//!
//! Non-sender fields become **positional** CLI args (in proto field order).
//! The sender/signer field is emitted as `--from key_name` via [`TxOptions`],
//! and canonical tx flags are appended by `chain_exec_tx_with`.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use heck::ToSnakeCase;

use crate::cli_mapping::{is_sender_field, map_proto_type, CliRendering};
use crate::naming;
use crate::proto_parser::ParsedService;

/// Generate a Rust source string containing the execute extension trait.
///
/// If `crate_path` is `"crate"`, paths will be `crate::chain::Chain` etc.
/// (for code checked into the ict-rs crate itself).
/// If `"ict_rs"`, paths will be `ict_rs::chain::Chain` etc.
/// (for code generated by downstream build.rs scripts).
pub fn generate_msg_trait(service: &ParsedService) -> String {
    generate_msg_trait_with_path(service, "crate")
}

/// Generate with an explicit crate path prefix.
pub fn generate_msg_trait_with_path(service: &ParsedService, crate_path: &str) -> String {
    let module = naming::module_from_package(&service.package);
    let trait_name = format_ident!("{}", naming::msg_trait_name(&module));
    let krate: TokenStream = crate_path.parse().unwrap();

    let mut methods = Vec::new();

    for rpc in &service.rpcs {
        let method_name = format_ident!("{}", naming::method_name(&module, &rpc.name));
        let action_kebab = naming::cli_action(&rpc.name);

        let signer = rpc
            .signer_field
            .as_deref()
            .unwrap_or("sender");

        // Build params (skip sender/signer)
        let non_sender_fields: Vec<_> = rpc
            .input_fields
            .iter()
            .filter(|f| !is_sender_field(&f.name) && f.name != signer)
            .collect();

        let param_decls: Vec<TokenStream> = non_sender_fields
            .iter()
            .map(|f| {
                let name = format_ident!("{}", f.name.to_snake_case());
                quote! { #name: &str }
            })
            .collect();

        // All non-sender fields are positional args in proto field order
        let field_pushes: Vec<TokenStream> = non_sender_fields
            .iter()
            .map(|f| {
                let name = format_ident!("{}", f.name.to_snake_case());
                let cli_param = map_proto_type(f.proto_type, &f.type_name);
                match cli_param.rendering {
                    CliRendering::BoolFlag => quote! {
                        if #name == "true" {
                            args.push("true".to_string());
                        }
                    },
                    _ => quote! {
                        args.push(#name.to_string());
                    },
                }
            })
            .collect();

        let module_str = &module;
        methods.push(quote! {
            async fn #method_name(
                &self, key_name: &str, #(#param_decls),*
            ) -> #krate::error::Result<#krate::tx::Tx> {
                let mut args: Vec<String> = vec![
                    "tx".to_string(),
                    #module_str.to_string(),
                    #action_kebab.to_string(),
                ];
                #(#field_pushes)*
                let opts = self.default_tx_opts().from(key_name);
                let arg_refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
                let output = self.chain_exec_tx_with(&arg_refs, opts).await?;
                #krate::cli::parse_tx_response(&output)
            }
        });
    }

    let tokens = quote! {
        #[#krate::cli::async_trait]
        pub trait #trait_name: #krate::chain::Chain {
            #(#methods)*
        }

        impl<T: #krate::chain::Chain + ?Sized> #trait_name for T {}
    };

    tokens.to_string()
}
