[package]
name = "scripts"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "delegations"
path = "bin/delegations.rs"

[[bin]]
name = "e2e"
path = "bin/e2e.rs"
[[bin]]
name = "ibc"
path = "bin/ibc_info.rs"

[features]
default = ["docker", "nostr"]
docker = []
nostr = []
# zk = ["cosmwasm-std/zk", "dep:zk-test-press"]
hash-market = ["dep:hash-market"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.89"
axum = { version = "0.7" }
clap = { version = "4", features = ["derive"] }
cosmwasm-schema = { path = "../../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../../cosmwasm/packages/std" }
csv = "1.4.0"
cw-orch = { path = "../../cw-orchestrator/cw-orch", features = ["daemon"] }
cw-orch-interchain = { path = "../../cw-orchestrator/cw-orch-interchain", features = ["daemon"] }
dotenv = "0.15"
env_logger = "0.11"
hash-market = { path = "../tools/hash-market", features = ["server", "client", "ve", "blossom"], optional = true }
hex = "0.4"
# zk-test-press = { path = "../../headstash/test-press", features = ["interface"], optional = true }
ict-rs = { path = "../../ict-rs/ict-rs", features = ["docker", "terp", "testing", "nostr"] }
k256 = "0.13.4"
log = "0.4.30"
reqwest = "0.13.4"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3.27.0"
terp-account-scripts = { path = "../../terp-account-billboards/scripts" }
terp-rs  = { path = "../crates/sdk" }
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
tracing = "0.1"
tracing-subscriber = "0.3.23"
which = "8.0.2"
