#!/usr/bin/env python3
"""
Overview Generator for the Abstract monorepo.

Generates a markdown dashboard (OVERVIEW.md at repo root) with project tables,
dependency stats, migration status, and diagnostic warnings.

Usage:
    dep-overview.py                       # generate OVERVIEW.md (repo root)
    dep-overview.py --output path.md      # custom output path
"""

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from dep_common import (
    DEVOPS_DIR,
    REPO_ROOT,
    discover_projects,
    load_matrix,
    load_migration_progress,
    matrix_pkg_names,
    pkg_to_matrix,
    run_diagnostics,
    scan_project,
)


STATUS_ICONS = {
    "green": ":green_circle:",
    "yellow": ":yellow_circle:",
    "red": ":red_circle:",
    "skipped": ":white_circle:",
}


def build_overview():
    """Build the full overview data structure."""
    matrix = load_matrix()
    migration = load_migration_progress()
    projects = discover_projects()

    # Index migration data by name
    mig_by_name = {}
    mig_by_path = {}
    for m in migration:
        mig_by_name[m.get("name", "")] = m
        mig_by_path[m.get("path", "")] = m

    # Scan all projects
    scans = []
    for proj in projects:
        scan = scan_project(proj, matrix)
        run_diagnostics(scan, matrix)
        scans.append(scan)

    return matrix, migration, scans, mig_by_name, mig_by_path


def get_migration_entry(scan, mig_by_name, mig_by_path):
    """Find the migration entry for a project."""
    name = scan.project.name
    path = scan.project.rel_path

    # Direct name match
    if name in mig_by_name:
        return mig_by_name[name]
    if path in mig_by_path:
        return mig_by_path[path]

    # Try stripping abstract- prefix for abstract sub-workspaces
    if name.startswith("abstract-"):
        short = name.replace("abstract-", "", 1)
        if short in mig_by_name:
            return mig_by_name[short]

    # For abstract sub-workspaces, try "abstract" entry with abstract/framework path
    if path.startswith("abstract/"):
        if "abstract" in mig_by_name:
            # Only match framework to the "abstract" migration entry
            if path == "abstract/framework":
                return mig_by_name["abstract"]

    return None


def generate_markdown(matrix, migration, scans, mig_by_name, mig_by_path) -> str:
    """Generate the OVERVIEW.md content."""
    lines = []
    today = date.today().isoformat()

    # ── Header ───────────────────────────────────────────────────────────
    lines.append("# Abstract Monorepo Overview")
    lines.append("")
    lines.append(f"*Auto-generated by `dep-overview.py` on {today}*")
    lines.append("")

    # ── Summary ──────────────────────────────────────────────────────────
    total_projects = len(scans)
    total_members = sum(len(s.project.member_tomls) for s in scans)
    total_deps = sum(
        s.path_dep_count + s.git_dep_count + s.registry_dep_count for s in scans
    )
    total_patches = sum(s.patch_count for s in scans)

    mig_check = [m for m in migration if m.get("cargo_check") == "green"]
    mig_test_green = [m for m in migration if m.get("cargo_test") == "green"]
    mig_test_red = [m for m in migration if m.get("cargo_test") == "red"]

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Projects:** {total_projects}")
    lines.append(f"- **Workspace members:** {total_members}")
    lines.append(f"- **Total dep entries:** {total_deps}")
    lines.append(f"- **Total patches:** {total_patches}")
    lines.append(f"- **Matrix crates:** {len(matrix)}")
    lines.append(f"- **Migration check pass:** {len(mig_check)}/{len(migration)}")
    lines.append(
        f"- **Migration test pass:** {len(mig_test_green)}/{len(migration)} "
        f"({len(mig_test_red)} red)"
    )
    lines.append("")

    # ── Group projects by migration layer ────────────────────────────────
    # Build layer ordering from migration-progress.yaml comments/structure
    layer_order = [
        "Foundation Layer",
        "Core CW Libraries",
        "Test Frameworks",
        "Application Contracts",
        "Core SDK + Orchestrator",
        "Other",
    ]

    # Map migration entries to layers based on position in yaml
    layer_map = {}
    current_layer = "Other"
    for m in migration:
        name = m.get("name", "")
        # Infer layer from known groupings
        if name in ("tendermint-rs", "cosmos-rust", "ibc-proto-rs"):
            current_layer = "Foundation Layer"
        elif name in ("cw-minus", "cw-plus", "cw-plus-plus", "cw-asset", "cw-nfts"):
            current_layer = "Core CW Libraries"
        elif name in (
            "cw-multi-test-fork", "clone-cw-multi-test",
            "osmosis-test-tube", "neutron-test-tube", "neutron-std", "osmosis-rust",
        ):
            current_layer = "Test Frameworks"
        elif name in (
            "polytone", "cw-ibc-demo", "wynddex", "wynd-lsd",
            "dao-contracts", "xion-account", "cw-packages", "abstract-cw-plus",
        ):
            current_layer = "Application Contracts"
        elif name in ("cw-orchestrator", "abstract"):
            current_layer = "Core SDK + Orchestrator"
        elif name in ("proxy-accounts", "new-cosmic-wavs", "halo2-axiom"):
            current_layer = "Other"
        layer_map[name] = current_layer

    # Group scans by layer
    grouped = {layer: [] for layer in layer_order}
    for scan in scans:
        mig = get_migration_entry(scan, mig_by_name, mig_by_path)
        if mig:
            layer = layer_map.get(mig.get("name", ""), "Other")
        else:
            layer = "Other"
        grouped[layer].append((scan, mig))

    # ── Project Table ────────────────────────────────────────────────────
    lines.append("## Projects")
    lines.append("")

    for layer in layer_order:
        items = grouped[layer]
        if not items:
            continue

        lines.append(f"### {layer}")
        lines.append("")
        lines.append(
            "| Project | Path | Members | Path | Git | Reg | Patches | Check | Test |"
        )
        lines.append(
            "|---------|------|--------:|-----:|----:|----:|--------:|-------|------|"
        )

        for scan, mig in items:
            proj = scan.project
            name_display = proj.name
            if proj.has_readme:
                name_display = f"[{proj.name}]({proj.rel_path}/README.md)"

            members = len(proj.member_tomls) if proj.is_workspace else 0

            check_icon = ""
            test_icon = ""
            if mig:
                check_icon = STATUS_ICONS.get(mig.get("cargo_check", ""), "")
                test_icon = STATUS_ICONS.get(mig.get("cargo_test", ""), "")

            lines.append(
                f"| {name_display} | `{proj.rel_path}` | {members} "
                f"| {scan.path_dep_count} | {scan.git_dep_count} "
                f"| {scan.registry_dep_count} | {scan.patch_count} "
                f"| {check_icon} | {test_icon} |"
            )

        lines.append("")

    # ── Diagnostics ──────────────────────────────────────────────────────
    all_diags = []
    for scan in scans:
        all_diags.extend(scan.diagnostics)

    if all_diags:
        lines.append("## Dependency Health")
        lines.append("")
        warnings = [d for d in all_diags if d.startswith("[WARN]")]
        infos = [d for d in all_diags if d.startswith("[INFO]")]

        if warnings:
            lines.append(f"**Warnings ({len(warnings)}):**")
            lines.append("")
            for w in warnings:
                lines.append(f"- {w}")
            lines.append("")

        if infos:
            lines.append(f"**Info ({len(infos)}):**")
            lines.append("")
            for i in infos:
                lines.append(f"- {i}")
            lines.append("")

    # ── Matrix Coverage ──────────────────────────────────────────────────
    lines.append("## Matrix Coverage")
    lines.append("")
    lines.append(
        "| Matrix Crate | Package | Stable | Consumers (matrix) | Found In |"
    )
    lines.append("|-------------|---------|--------|--------------------|----------|")

    lookup = pkg_to_matrix(matrix)
    known = matrix_pkg_names(matrix)

    # Build project name -> rel_path map for linking
    proj_paths = {scan.project.name: scan.project.rel_path for scan in scans}

    # Build actual consumer map from scans
    actual_consumers = {}  # pkg_name -> set of project names
    for scan in scans:
        for dep in scan.member_deps:
            pkg = dep.pkg_name
            if pkg in known:
                actual_consumers.setdefault(pkg, set()).add(scan.project.name)

    def _link_names(names, paths_map):
        """Turn project names into markdown links to their Cargo.toml."""
        parts = []
        for n in names:
            if n in paths_map:
                parts.append(f"[{n}]({paths_map[n]}/Cargo.toml)")
            else:
                parts.append(n)
        return ", ".join(parts)

    for key, info in sorted(matrix.items()):
        pkg = info.get("package", key)
        stable = info.get("stable", "N/A")
        declared = info.get("consumers", [])
        actual = sorted(actual_consumers.get(pkg, set()))

        declared_str = ", ".join(declared)
        actual_str = _link_names(actual, proj_paths)

        lines.append(
            f"| {key} | {pkg} | {stable} | {declared_str} | {actual_str} |"
        )

    lines.append("")

    # ── Migration Blockers ───────────────────────────────────────────────
    blockers = [
        m for m in migration
        if m.get("blockers") and m["blockers"] != []
    ]
    if blockers:
        lines.append("## Active Blockers")
        lines.append("")
        for m in blockers:
            lines.append(f"**{m['name']}:**")
            for b in m.get("blockers", []):
                lines.append(f"- {b}")
            lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate monorepo overview markdown")
    parser.add_argument("--output", help="Output path (default: _devops/OVERVIEW.md)")
    args = parser.parse_args()

    matrix, migration, scans, mig_by_name, mig_by_path = build_overview()
    md = generate_markdown(matrix, migration, scans, mig_by_name, mig_by_path)

    output_path = Path(args.output) if args.output else REPO_ROOT / "OVERVIEW.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md)
    print(f"Wrote {output_path} ({len(md)} bytes)")


if __name__ == "__main__":
    main()
