use crate::wallet::wallet::HeadstashMetadata;
use crate::wallet::HeadstashWallet;
use crate::{Error, Network};

use serde::{Deserialize, Serialize};
use std::str::FromStr;
use wasm_bindgen::prelude::*;

use zk_headstash::address::RecpAddr;
use zk_headstash::r#gen::headstash::snp::v1::SerializedNoteData;
use zk_headstash::keys::EligibleSk;
use zk_headstash::note::{Nullifier, Rho};
use zk_headstash::value::HeadstashValue;

/// HeadstashWallet - Database and state manager for MetaMask Snap plugin
///
/// This wallet is a database that maintains headstash note data indexed by headstash ID.
///
/// ## Architecture
///
/// ### headstash file index
/// we store one `headstash_<>.yaml` per headstash instance per wallet.
/// this file contains the
/// - list of tokens allocated to a wallet for a headstash,
/// - an encrypted tally of spent fdi for each denom.
///
/// This file can either be manually generated by a user, or created by downloading the entire headstash-genesis file that contains an accounts allocation.
///
///
/// ### networking configuration
/// There are two main grpc connections:
/// - one to the headstash api networking layer for syncing data,
/// - one to Terp Network (cosmos-grpc).
/// We are able to broadcast and retrieve data for both through a unified client api, and define how to
///
/// BroadcastMethod::{Direct,Proxy}
///
/// ### Proof generation
/// this snap does not create proofs, but rather serializes both the public (instances) & private values required by the headstash circuit,
/// and responds with exactly just the required data to be able to generate a proof. This acts like a secure enclave between a users secret key,
/// ensuring it never leaves or is exposed from the wallet.
///
/// ## Design Principles
///
/// 1. **No Secret Key Storage**: ESK only requested from MetaMask when needed for operations
/// 2. **Indexed Storage**: All data indexed by headstash contract address
/// 3. **gRPC Communication**: Reuses zcash-style gRPC patterns for headstash API
/// 4. **Minimal Friction**: Designed to minimize refactor effort from zcash wallet

/// # A Headstash Wallet for MetaMask Snap
///
/// ## Key Security Principles
///
/// 1. **No Secret Key Storage**: The wallet NEVER stores secret keys. Keys are only
///    requested from MetaMask when needed for specific operations.
/// 2. **Encrypted State**: All persistent state can be encrypted using MetaMask's
///    snap_manageState API for secure storage.

/// ## Creating a Wallet
///
/// ```javascript
/// const wallet = new WebWallet("main", "https://headstash-api.terp.network", 10);
/// ```
///
/// ## Discovering Headstashes
///
/// Before claiming, discover available headstashes via the market contract:
///
/// ```javascript
/// const headstashes = await wallet.discover_headstashes();
/// for (const headstash of headstashes) {
///     console.log(`Found: ${headstash.contract_addr}`);
/// }
/// ```
///
/// ## Generating Notes
///
/// Generate notes client-side from the Merkle tree:
///
/// ```javascript
/// // Request secret key from MetaMask
/// const esk = await snap.request({ method: "get_secret_key" });
///
/// await wallet.generate_notes_for_headstash(
///     "terp1contract123",
///     esk
/// );
/// ```
///
/// ## Claiming Allocations
///
/// Three pathways for claiming:
///
/// ### 1. Manual (pay your own gas)
/// ```javascript
/// await wallet.claim_via_manual(hid, esk, nullifier);
/// ```
///
/// ### 2. Feegrant (request gas from headstash-server)
/// ```javascript
/// await wallet.claim_via_feegrant(hid, esk, nullifier);
/// ```
///
/// ### 3. Smart Account (gasless via authenticator)
/// ```javascript
/// await wallet.claim_via_smart_account(hid, esk, nullifier);
/// ```
///
/// ## State Persistence
///
/// Serialize wallet state for MetaMask storage:
///
/// ```javascript
/// const state = await wallet.db_to_bytes();
/// await snap.request({
///     method: "snap_manageState",
///     params: { operation: "update", newState: { wallet: state } }
/// });
/// ```
///
#[wasm_bindgen]
pub struct WebWallet {
    inner: HeadstashWallet,
}

#[wasm_bindgen]
impl WebWallet {
    /// Create a new Headstash wallet instance
    #[wasm_bindgen(constructor)]
    pub async fn new(
        network: &str,
        headstash_api_url: &str,
        cosmos_grpc_url: Option<String>,
    ) -> Result<WebWallet, Error> {
        let network = Network::from_str(network)?;
        let inner = HeadstashWallet::new(network, Some(headstash_api_url)).await?;
        Ok(Self { inner })
    }

    /// Generate note data (nullifier, commitment, nk) from secret key and note inputs
    pub async fn gen_claim(
        &self,
        nd: String,
        v: String,
        fdi: u64,
        recp_hex: String,
        esk_hex: String,
        rho_hex: String,
        rseed_hex: String,
    ) -> Result<String, Error> {
        // Generate note data
        let (nk, nullifier, cm) = self.inner.generate_note_data(
            EligibleSk::from_hex(&esk_hex),
            Rho::from_bytes(
                hex::decode(&rho_hex)
                    .map_err(|e| Error::KeyDecoding(format!("Invalid rho hex: {}", e)))?
                    .as_slice()
                    .try_into()
                    .map_err(|_| Error::KeyDecoding("Invalid rho length".into()))?,
            )
            .expect("rho from bytes"),
            HeadstashValue::from_raw(
                v.parse()
                    .map_err(|e| Error::KeyDecoding(format!("Invalid value: {}", e)))?,
                &nd,
                fdi,
            )
            .unwrap(),
            RecpAddr::new(
                hex::decode(&recp_hex)
                    .map_err(|e| Error::KeyDecoding(format!("Invalid recp hex: {}", e)))?
                    .try_into()
                    .expect("darn"),
            ),
            hex::decode(&rseed_hex)
                .map_err(|e| Error::KeyDecoding(format!("Invalid rseed hex: {}", e)))?
                .as_slice()
                .try_into()
                .map_err(|_| Error::KeyDecoding("Invalid rseed length".into()))?,
        )?;

        // Serialize as JSON
        let note_data = SerializedNoteData {
            nk: nk.to_bytes().to_vec(),
            nul: nullifier.to_bytes().to_vec(),
            cm: zk_headstash::note::ExtractedNoteCommitment::from(cm)
                .to_bytes()
                .to_vec(),
            v,
            nd,
            fdi,
            spent: false,
            recp: 0,
        };

        serde_json::to_string(&note_data)
            .map_err(|e| Error::KeyDecoding(format!("JSON serialization failed: {}", e)))
    }

    /// Claim headstash instance via headstash proxy mesh network to bootstrap new account.
    /// Can also optionally pass a msg to register an MsgAddAuthenticator for a newly bootstrapped account, which is the one recieving the claimed funds in a headstash instance.
    /// If adding an authenticator, will return the newly generated keys secret key, which front ends can add to clipboard & prompt an import wallet
    pub async fn claim_headstash(
        &self,
        hid: String, // contract addr
        esk_hex: String,
        nullifier_hex: String,
    ) -> Result<String, Error> {
        let esk = EligibleSk::from_hex(&esk_hex);
        let nf = Nullifier::from_bytes(
            hex::decode(&nullifier_hex)
                .map_err(|e| Error::KeyDecoding(format!("Invalid nullifier hex: {}", e)))?
                .as_slice()
                .try_into()
                .map_err(|_| Error::KeyDecoding("Invalid nullifier length".into()))?,
        )
        .expect("nullifier from bytes");
        let hmd = HeadstashMetadata {
            nf,
            mr: todo!(),
            mp: todo!(),
            hv: todo!(),
            recp: todo!(),
        };

        let response = self
            .inner
            .claim_headstash_via_smart_account(hid, esk, hmd)
            .await?;

        serde_json::to_string(&response)
            .map_err(|e| Error::KeyDecoding(format!("JSON serialization failed: {}", e)))
    }
}
