[package]
name = "cw721-nips"
version = "0.1.0"
edition = "2021"
description = "Nostr NIP library with cw721-trait-based metadata system"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8.22"
cosmwasm-schema  = { path = "../../../../cosmwasm/packages/schema", optional = true }
cosmwasm-std = { path = "../../../../cosmwasm/packages/std", optional = true }
cw721 = { path = "../../../../cw-nfts/packages/cw721", optional = true }
serde_json = "1.0"
hex = "0.4"
sha2 = "0.10"
thiserror = "1.0"

# NIP-44 v2
base64 = {version = "0.22", optional = true}
chacha20 = {version = "0.9", optional = true}
constant_time_eq = {version = "0.3", optional = true}
hkdf = {version = "0.12", optional = true}
hmac = {version = "0.12", optional = true}
uuid = {version = "1.23.1", optional = true, deafult-features = false}
rand_core = { version = "0.6", features = ["getrandom"] , optional = true }
axum = { version = "0.7" }

[features]
default = ["full"]
nip01 = []
nip15 = []
nip52 = []
nip77 = ["dep:uuid"]
nip44 = ["dep:rand_core","dep:hmac","dep:hkdf","dep:constant_time_eq","dep:chacha20","dep:base64"]
cw = ["dep:cosmwasm-std","dep:cosmwasm-schema", "dep:cw721"]
full = ["cw","nip01", "nip15", "nip52", "nip77"]