[package]
name = "cw-headstash-factory"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
library = []

[dependencies]
ark-bls12-381 = "0.5.0"
cw-headstash = { workspace = true }
cw-ownable  = { workspace = true }
cw-storage-plus = { workspace = true }
cw-orch = { workspace = true, optional = true }
# cw20 = "2.0.0"
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true, features = ["cosmwasm_2_0"] }
serde = { workspace = true }
thiserror = "1.0"

[dev-dependencies]