[package]
name = "no-rick"
version = "0.2.0"
authors = ["A Hardnett"]
edition = "2024"


[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp", features = ["cosmwasm_1_4","cosmwasm_3_0", "stargate"] }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp", library = "cosmwasm-schema" }
thiserror = { version = "2.0.16" }
pasta_curves = "0.5"
ff = "0.13"
lol_alloc = "0.4.1"
prost = "0.14"
rand_core = "0.6"

# for local development
#cosmwasm-std = { path = "../../../../../zk-cosmwasm/mvp/packages/std" }
#cosmwasm-schema = { path = "../../../../../zk-cosmwasm/mvp/packages/schema" }

[dev-dependencies]

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
