[package]
name          = "terp-dao"
description   = "A custom fantoken minter, being used as an event ticketing distribution."
authors       = [""]
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema    = { workspace = true }
cw-storage-plus    = { workspace = true }
cosmwasm-std       = { workspace = true }
terp-auth          = { workspace = true }
terp-account       = { workspace = true }
cw2                = { workspace = true }
serde              = { workspace = true }
thiserror          = { workspace = true }


[dev-dependencies]