//! Go type generation from CosmWasm merged schemas.
//!
//! Uses the type-mapping primitives from the existing cosmwasm go-gen
//! crate (crates/cosmwasm/packages/go-gen/). The key functions here mirror
//! the logic in main.rs, schema.rs, and go.rs from that crate: custom type
//! mappings (Uint128 -> string, Binary -> []byte, Addr -> string, etc.),
//! proper $ref resolution, oneOf enum variant handling, inline object
//! struct generation, nullability (Nullable/NonNullable/OmitEmpty), and
//! acronym replacement (Ibc -> IBC, Id -> ID, Url -> URL, Uri -> URI).
//!
//! Unlike the go-gen crate which processes a single RootSchema, this
//! generator extracts individual message types (instantiate, execute, query,
//! migrate, sudo) and all definitions from a merged CosmWasm schema JSON,
//! then generates Go code annotated with json tags.

use crate::config::GenerationContext;
use crate::resolver::SourceResolver;
use crate::{GenerationResult, Generator};
use std::collections::{HashMap, HashSet};

pub struct GoGenGenerator;

impl Generator for GoGenGenerator {
    fn name(&self) -> &'static str {
        "go"
    }

    fn enabled_by_default(&self) -> bool {
        true
    }

    fn generate(&self, ctx: &GenerationContext) -> anyhow::Result<GenerationResult> {
        let go_out = &ctx.go_out;
        std::fs::create_dir_all(go_out)?;

        let (_label, groups) = SourceResolver::resolve_grouped(ctx);
        if groups.is_empty() {
            log::warn!("[go] No schema directories found");
            return Ok(GenerationResult {
                name: "go",
                success: true,
                files_generated: 0,
                output_dir: Some(go_out.to_string_lossy().to_string()),
                message: Some("No schema dirs found, skipping".into()),
            });
        }

        let mut total_files = 0;
        for (contract_name, schemas) in &groups {
            for (_stem, merged) in schemas {
                let go_name = to_pascal_case(contract_name);
                let pkg_name = contract_name.to_lowercase()
                    .replace('-', "")
                    .replace('.', "")
                    .replace('_', "");
                let mut output = String::new();
                output.push_str(&format!("package {}\n\n", pkg_name));
                output.push_str("// Code generated by gen-tools (cosmwasm-go-gen primitives) — DO NOT EDIT.\n\n");

                // Message types to extract from the merged schema
                let msg_keys = ["instantiate", "execute", "query", "migrate", "sudo"];
                let mut all_defs: HashMap<String, serde_json::Value> = HashMap::new();
                let mut message_types: Vec<(String, serde_json::Value)> = Vec::new();

                for key in &msg_keys {
                    if let Some(msg_val) = merged.get(*key) {
                        if msg_val.is_null() {
                            continue;
                        }
                        let title = msg_val.get("title")
                            .and_then(|v| v.as_str())
                            .unwrap_or(key)
                            .to_string();
                        // Collect definitions from this message type
                        collect_defs(msg_val, &mut all_defs);
                        message_types.push((title, msg_val.clone()));
                    }
                }

                // Response types
                let mut response_types: Vec<(String, serde_json::Value)> = Vec::new();
                if let Some(responses) = merged.get("responses").and_then(|v| v.as_object()) {
                    for (qname, resp_schema) in responses {
                        let title = resp_schema.get("title")
                            .and_then(|v| v.as_str())
                            .unwrap_or(qname)
                            .to_string();
                        collect_defs(resp_schema, &mut all_defs);
                        response_types.push((title, resp_schema.clone()));
                    }
                }

                // Generate Go types from definitions (sorted for stability)
                let mut def_names: Vec<String> = all_defs.keys().cloned().collect();
                def_names.sort();
                for name in &def_names {
                    let schema = &all_defs[name];
                    let go_type = def_to_go_type(name, schema, &all_defs);
                    output.push_str(&go_type);
                    output.push('\n');
                }

                // Generate message types — these are oneOf enums, rendered as struct
                for (title, schema) in &message_types {
                    let go_type = def_to_go_type(title, schema, &all_defs);
                    output.push_str(&go_type);
                    output.push('\n');
                }

                // Generate response types
                for (title, schema) in &response_types {
                    let go_type = def_to_go_type(title, schema, &all_defs);
                    output.push_str(&go_type);
                    output.push('\n');
                }

                // Write file
                let go_file_name = format!("{}.go", contract_name.replace('-', "_"));
                let go_path = go_out.join(&go_file_name);
                std::fs::write(&go_path, &output)?;
                total_files += 1;
                log::info!("[go] Wrote {:?} ({} defs + {} msgs + {} responses)",
                    go_path, all_defs.len(), message_types.len(), response_types.len());
            }
        }

        Ok(GenerationResult {
            name: "go",
            success: true,
            files_generated: total_files,
            output_dir: Some(go_out.to_string_lossy().to_string()),
            message: Some(format!("{} Go files generated", total_files)),
        })
    }
}

/// Collect all definitions nested in a schema value into the all_defs map.
fn collect_defs(schema: &serde_json::Value, all_defs: &mut HashMap<String, serde_json::Value>) {
    if let Some(defs) = schema.get("definitions").and_then(|v| v.as_object()) {
        for (dn, dv) in defs {
            all_defs.entry(dn.clone()).or_insert_with(|| dv.clone());
        }
    }
    // Also recurse into oneOf variants (each variant may have its own definitions)
    if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
        for variant in variants {
            collect_defs(variant, all_defs);
        }
    }
}

/// Convert a JSON Schema definition (or message type) to a Go type definition.
/// Returns the complete Go type string including type declaration.
fn def_to_go_type(name: &str, schema: &serde_json::Value,
                  defs: &HashMap<String, serde_json::Value>) -> String {
    let go_name = replace_acronyms(to_pascal_case(name));

    // oneOf -> rendered as struct with nullable pointer fields (enum pattern)
    if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
        return one_of_to_struct(&go_name, variants, schema, defs);
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("object") => {
            let mut out = format!("type {} struct {{\n", go_name);
            if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
                let required: HashSet<&str> = schema.get("required")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().filter_map(|r| r.as_str()).collect())
                    .unwrap_or_default();

                for (field_name, field_schema) in props {
                    let ft = resolve_go_type(field_schema, defs, name, field_name);
                    let pascal = to_pascal_case(field_name);
                    let tag = field_name;
                    let omit = if !required.contains(field_name.as_str()) {
                        ",omitempty"
                    } else {
                        ""
                    };
                    out.push_str(&format!("\t{} {} `json:\"{}{}\"`\n", pascal, ft, tag, omit));
                }
            }
            out.push_str("}\n");
            out
        }
        Some("string") => {
            if let Some(variants) = schema.get("enum").and_then(|v| v.as_array()) {
                let mut out = format!("type {} string\n\nconst (\n", go_name);
                for (i, variant) in variants.iter().enumerate() {
                    if let Some(v) = variant.as_str() {
                        let const_name = format!("{}_{}", go_name, to_pascal_case(v));
                        out.push_str(&format!("\t{} {} = \"{}\"\n", const_name, go_name, v));
                        if i == 0 {
                            out.push_str("\t// Default value\n");
                        }
                    }
                }
                out.push_str(")\n");
                out
            } else {
                format!("type {} = string\n", go_name)
            }
        }
        Some("array") => {
            let inner = schema.get("items")
                .map(|i| resolve_go_type(i, defs, name, "items"))
                .unwrap_or_else(|| "interface{}".to_string());
            format!("type {} = []{}\n", go_name, inner)
        }
        Some("integer") => {
            let fmt = schema.get("format").and_then(|v| v.as_str()).unwrap_or("uint64");
            format!("type {} = {}\n", go_name, map_int_format(fmt))
        }
        _ => {
            // anyOf/type-less -> interface{}
format!("type {} interface{}\n", go_name, "{ }")
        }
    }
}

/// oneOf -> Go struct with nullable pointer fields (CosmWasm enum pattern).
fn one_of_to_struct(name: &str, variants: &[serde_json::Value],
                    parent_schema: &serde_json::Value,
                    defs: &HashMap<String, serde_json::Value>) -> String {
    let docs = parent_schema
        .get("title")
        .and_then(|v| v.as_str())
        .map(|t| format!("// {} is a Cosmos message variant\n", name))
        .unwrap_or_default();

    let mut out = format!("type {} struct {{\n", name);
    for (i, variant) in variants.iter().enumerate() {
        // Each variant is either a $ref or inline object with single property
        let (field_name, field_type) = if let Some(ref_path) = variant.get("$ref").and_then(|v| v.as_str()) {
            let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
            let rt = replace_acronyms(to_pascal_case(ref_name));
            // The wrapper field is the variant's "title" or "wrapper"
            (to_camel_case(ref_name), rt)
        } else if let Some(props) = variant.get("properties").and_then(|v| v.as_object()) {
            if props.len() == 1 {
                let (fn_name, fv) = props.iter().next().unwrap();
                let ft = resolve_go_type(fv, defs, name, fn_name);
                (fn_name.clone(), ft)
            } else {
                // inline struct - generate name from position
                let inline_name = format!("{}{}", name, to_pascal_case( &format!("Variant{}", i)));
                let ft = def_to_go_type(&inline_name, variant, defs);
                out.insert_str(out.len()-3, &format!(";\n{}", ft.trim()));
                (format!("variant_{}", i), inline_name)
            }
        } else {
            // String-only variant (no inner data)
            (format!("variant_{}", i), "string".to_string())
        };
        // In cosmwasm enums in Go, each variant is a nullable pointer
        // with omitempty for the json tag where inner fields live
        let ptr = if field_type == "interface{}" { "" } else { "*" };
        out.push_str(&format!("\t{}{} {} `json:\"{},omitempty\"`\n",
            ptr, to_pascal_case(&field_name), field_type, field_name));
    }
    out.push_str("}\n");
    out
}

/// Resolve a JSON Schema to a Go type name, handling $ref, oneOf, allOf,
/// anyOf (nullable), arrays, primitives, and inline objects.
fn resolve_go_type(schema: &serde_json::Value,
                   defs: &HashMap<String, serde_json::Value>,
                   parent_name: &str,
                   field_name: &str) -> String {
    // 1) Unwrap allOf wrapping — single-$ref allOf: [{$ref: "..."}]
    //    This is the nullability pattern schemars uses for option<addr> etc.
    if let Some(allof) = schema.get("allOf").and_then(|v| v.as_array()) {
        if allof.len() == 1 {
            if let Some(ref_path) = allof[0].get("$ref").and_then(|v| v.as_str()) {
                let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
                return map_custom_type(ref_name);
            }
        }
    }

    // 2) Unwrap anyOf with null (nullable pattern: anyOf: [{$ref: ...}, {type: "null"}])
    if let Some(anyof) = schema.get("anyOf").and_then(|v| v.as_array()) {
        // Filter out null variants
        let non_null: Vec<&serde_json::Value> = anyof.iter()
            .filter(|v| v.get("type").and_then(|t| t.as_str()) != Some("null"))
            .collect();
        if non_null.len() == 1 {
            // Single non-null variant — resolve it recursively
            return resolve_go_type(non_null[0], defs, parent_name, field_name);
        }
        // Multiple non-null variants or complex anyOf — interface{}
        return "interface{}".to_string();
    }

    // 3) Handle type as array (schemars outputs ["integer", "null"] for optional ints)
    if let Some(types) = schema.get("type").and_then(|v| v.as_array()) {
        for t in types {
            if let Some(type_str) = t.as_str() {
                if type_str != "null" {
                    // Create a synthetic schema with just this type
                    let mut single = serde_json::Map::new();
                    single.insert("type".to_string(), serde_json::Value::String(type_str.to_string()));
                    // Preserve format for integers
                    if let Some(fmt) = schema.get("format").and_then(|v| v.as_str()) {
                        single.insert("format".to_string(), serde_json::Value::String(fmt.to_string()));
                    }
                    let syn = serde_json::Value::Object(single);
                    return resolve_go_type(&syn, defs, parent_name, field_name);
                }
            }
        }
    }

    // 4) $ref -> reference to a definition (direct, not allOf-wrapped)
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
        return map_custom_type(ref_name);
    }

    // 5) oneOf/anyOf (non-nullable) -> interface{}
    if schema.get("oneOf").is_some() {
        return "interface{}".to_string();
    }

    // 6) Type-based resolution
    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => {
            if let Some(fmt) = schema.get("format").and_then(|v| v.as_str()) {
                match fmt {
                    "uint64" | "int64" => return "string".to_string(),
                    "date-time" => return "string".to_string(),
                    _ => {}
                }
            }
            "string".to_string()
        }
        Some("integer") => {
            let fmt = schema.get("format").and_then(|v| v.as_str()).unwrap_or("uint64");
            map_int_format(fmt)
        }
        Some("number") => "string".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            let inner = schema.get("items")
                .map(|i| resolve_go_type(i, defs, parent_name, field_name))
                .unwrap_or_else(|| "interface{}".to_string());
            format!("[]{}", inner)
        }
        Some("null") => "interface{}".to_string(),
        _ => {
            // Inline object (no explicit type but has properties)
            if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
                let struct_name = format!("{}{}", to_pascal_case(parent_name), to_pascal_case(field_name));
                let mut out = format!("type {} struct {{\n", struct_name);
                let required: HashSet<&str> = schema.get("required")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().filter_map(|r| r.as_str()).collect())
                    .unwrap_or_default();
                for (field_name, fv) in props {
                    let pascal = to_pascal_case(field_name);
                    let ft = resolve_go_type(fv, defs, &struct_name, field_name);
                    let omit = if !required.contains(field_name.as_str()) { ",omitempty" } else { "" };
                    out.push_str(&format!("\t{} {} `json:\"{}{}\"`\n", pascal, ft, field_name, omit));
                }
                out.push_str("}\n");
                return struct_name;
            }
            "interface{}".to_string()
        }
    }
}

/// Map Rust/CosmWasm type names to Go types.
fn map_custom_type(name: &str) -> String {
    match name {
        "Addr" => "string",
        "Uint64" => "Uint64",
        "Uint128" => "string",
        "Uint256" => "string",
        "Uint512" => "string",
        "Int64" => "Int64",
        "Int128" => "string",
        "Int256" => "string",
        "Int512" => "string",
        "Decimal" => "string",
        "Decimal256" => "string",
        "Binary" => "[]byte",
        "HexBinary" => "string",
        "Checksum" => "Checksum",
        "Timestamp" => "Uint64",
        "Order" => "string",
        "VoteOption" => "voteOption",
        "ReplyOn" => "replyOn",
        "Coin" => "Coin",           // reference to defined struct
        "CoinInfo" => "CoinInfo",
        "TokenInfo" => "TokenInfo",
        "" => "interface{}",
        _ => name, // pass through as type reference
    }.to_string()
}

/// Format integer format strings.
fn map_int_format(fmt: &str) -> String {
    match fmt {
        "uint8" => "uint8", "int8" => "int8",
        "uint16" => "uint16", "int16" => "int16",
        "uint32" => "uint32", "int32" => "int32",
        "uint64" => "uint64", "int64" => "int64",
        _ => "uint64",
    }.to_string()
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut c = pascal.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().to_string() + c.as_str(),
    }
}

/// Replace acronyms matching the go-gen crate (Ibc -> IBC, Id -> ID, Url -> URL, Uri -> URI).
fn replace_acronyms(s: String) -> String {
    let mut s = s;
    // Only replace word boundaries: "Ibc" at end or before uppercase/non-ascii
    replace_word(&mut s, "Url", "URL");
    replace_word(&mut s, "Uri", "URI");
    replace_word(&mut s, "Id", "ID");
    replace_word(&mut s, "Ibc", "IBC");
    s
}

fn replace_word(s: &mut String, from: &str, to: &str) {
    if from.len() != to.len() {
        return;
    }
    let mut start = 0;
    while let Some(pos) = s[start..].find(from) {
        let end = start + pos + from.len();
        let next_char = s.chars().nth(end);
        match next_char {
            Some(c) if c.is_ascii_lowercase() => {}
            _ => {
                s.replace_range(start+pos..end, to);
            }
        }
        start = end;
    }
}