//! Python client library generation from CosmWasm schemas.
//!
//! Generates Python dataclasses and encode/decode methods from
//! CosmWasm JSON schema types, following the prost-to-pyo3.sh pattern
//! in terp-rs/scripts/gen/ but generalized for any contract schema.

use crate::config::GenerationContext;
use crate::resolver::SourceResolver;
use crate::{GenerationResult, Generator};
use std::collections::BTreeMap;

pub struct PythonGenGenerator;

impl Generator for PythonGenGenerator {
    fn name(&self) -> &'static str {
        "python"
    }

    fn enabled_by_default(&self) -> bool {
        true
    }

    fn generate(&self, ctx: &GenerationContext) -> anyhow::Result<GenerationResult> {
        let py_out = &ctx.py_out;
        std::fs::create_dir_all(py_out)?;

        let mut total_files = 0;

        let (_label, groups) = SourceResolver::resolve_grouped(ctx);
        if groups.is_empty() {
            log::warn!("[python] No type sources found");
            return Ok(GenerationResult {
                name: "python",
                success: true,
                files_generated: 0,
                output_dir: Some(py_out.to_string_lossy().to_string()),
                message: Some("No type sources found, skipping".into()),
            });
        }

        for (contract_name, schemas) in &groups {
            let py_content = generate_python_module(schemas, contract_name)?;
            let py_file = py_out.join(format!("{}.py", contract_name.replace('-', "_")));
            std::fs::write(&py_file, &py_content)?;
            total_files += 1;
            log::info!("[python] Wrote {:?}", py_file);

            // Generate __init__.py for the package
            let init_path = py_out.join("__init__.py");
            if !init_path.exists() {
                std::fs::write(&init_path, "# Auto-generated Python client library\n")?;
            }
        }

        Ok(GenerationResult {
            name: "python",
            success: true,
            files_generated: total_files,
            output_dir: Some(py_out.to_string_lossy().to_string()),
            message: Some(format!("{} Python modules generated", total_files)),
        })
    }
}

fn generate_python_module(
    schemas: &BTreeMap<String, serde_json::Value>,
    contract_name: &str,
) -> anyhow::Result<String> {
    let mut output = String::new();

    output.push_str(&format!(
        "# Auto-generated by gen-tools from {contract_name}\n"
    ));
    output.push_str("# Do not edit manually.\n\n");
    output.push_str("from __future__ import annotations\n\n");
    output.push_str("import json\n");
    output.push_str("from dataclasses import dataclass, field, asdict\n");
    output.push_str("from typing import Any, List, Optional\n\n");

    for (type_name, schema) in schemas {
        let class_name = schema
            .get("title")
            .and_then(|v| v.as_str())
            .unwrap_or(type_name);
        let clean_name = class_name
            .split(|c: char| !c.is_alphanumeric())
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("");

        if let Some(desc) = schema.get("description").and_then(|v| v.as_str()) {
            output.push_str(&format!("# {}\n", desc));
        }

        match schema.get("type").and_then(|v| v.as_str()) {
            Some("object") => {
                output.push_str(&format!("@dataclass\nclass {}:\n", clean_name));
                if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
                    for (field_name, field_schema) in props {
                        let (py_type, py_default) = json_type_to_python(field_schema);
                        output.push_str(&format!(
                            "    {}: {} = {}\n",
                            field_name, py_type, py_default
                        ));
                    }
                }
                output.push_str(&format!(
                    "    TYPE_URL: str = field(default='/{}/{}.v1.{}', init=False, repr=False)\n\n",
                    contract_name.replace('-', "_"),
                    contract_name.replace('-', "_"),
                    clean_name
                ));

                // Encode/decode methods
                output.push_str("    def encode(self) -> bytes:\n");
                output.push_str("        from contract_proto._native import encode_message\n");
                output.push_str("        return encode_message(self.TYPE_URL, json.dumps(asdict(self)).encode())\n\n");
                output.push_str("    @classmethod\n");
                output.push_str(&format!("    def decode(cls, data: bytes) -> '{}':\n", clean_name));
                output.push_str("        from contract_proto._native import decode_message\n");
                output.push_str("        return cls(**json.loads(decode_message(cls.TYPE_URL, data)))\n\n");
            }
            Some("string") if schema.get("enum").is_some() => {
                // String enum -> Python enum + str
                output.push_str("from enum import Enum\n\n");
                output.push_str(&format!("class {}(str, Enum):\n", clean_name));
                if let Some(variants) = schema.get("enum").and_then(|v| v.as_array()) {
                    for variant in variants {
                        if let Some(v) = variant.as_str() {
                            let var_name = v.to_uppercase().replace('-', "_");
                            output.push_str(&format!("    {} = '{}'\n", var_name, v));
                        }
                    }
                }
                output.push('\n');
            }
            _ => {
                // Type alias
                let (py_type, _) = json_type_to_python(schema);
                output.push_str(&format!("{} = {}\n\n", clean_name, py_type));
            }
        }
    }

    Ok(output)
}

/// Map JSON schema types to Python type annotations and defaults.
fn json_type_to_python(schema: &serde_json::Value) -> (String, String) {
    // $ref
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
        let clean = ref_name
            .split(|c: char| !c.is_alphanumeric())
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("");
        return ("Optional[".to_string() + &clean + "]", "None".to_string());
    }

    // oneOf/anyOf -> Any
    if let Some(_) = schema.get("oneOf").or_else(|| schema.get("anyOf")) {
        return ("Any".to_string(), "None".to_string());
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => ("str".to_string(), "\"\"".to_string()),
        Some("integer") => {
            if let Some(fmt) = schema.get("format").and_then(|v| v.as_str()) {
                if fmt == "uint64" || fmt == "int64" {
                    return ("str".to_string(), "\"0\"".to_string()); // Cosmos bigints
                }
            }
            ("int".to_string(), "0".to_string())
        }
        Some("number") => ("float".to_string(), "0.0".to_string()),
        Some("boolean") => ("bool".to_string(), "False".to_string()),
        Some("array") => {
            if let Some(items) = schema.get("items") {
                let (inner_type, _) = json_type_to_python(items);
                (
                    format!("List[{}]", inner_type),
                    "field(default_factory=list)".to_string(),
                )
            } else {
                (
                    "List[Any]".to_string(),
                    "field(default_factory=list)".to_string(),
                )
            }
        }
        Some("null") => ("None".to_string(), "None".to_string()),
        _ => ("Any".to_string(), "None".to_string()),
    }
}