//! README API markdown generation.
//!
//! Generates API documentation in Markdown format from CosmWasm schema files,
//! following the `generate_api_markdown(workspace_root: &Path)` pattern
//! defined in the dao-contracts test suite helper functions.

use crate::config::GenerationContext;
use crate::resolver::SourceResolver;
use crate::{GenerationResult, Generator};
use std::collections::BTreeMap;
use std::path::Path;

pub struct ReadmeApiGenerator;

impl Generator for ReadmeApiGenerator {
    fn name(&self) -> &'static str {
        "readme"
    }

    fn enabled_by_default(&self) -> bool {
        true
    }

    fn generate(&self, ctx: &GenerationContext) -> anyhow::Result<GenerationResult> {
        let mut total_files = 0;

        let (_label, groups) = SourceResolver::resolve_grouped(ctx);
        if groups.is_empty() {
            log::warn!("[readme] No type sources found");
            return Ok(GenerationResult {
                name: "readme",
                success: true,
                files_generated: 0,
                output_dir: None,
                message: Some("No type sources found, skipping".into()),
            });
        }

        // Generate per-contract API markdown
        for (contract_name, schemas) in &groups {
            let md = generate_contract_readme(schemas, contract_name)?;

            let docs_dir = ctx.workspace_root.join("docs").join("api");
            std::fs::create_dir_all(&docs_dir)?;
            let md_path = docs_dir.join(format!("{}.api.md", contract_name));
            std::fs::write(&md_path, &md)?;
            total_files += 1;
            log::info!("[readme] Wrote {:?}", md_path);
        }

        // Generate a root API overview README
        if total_files > 0 {
            let overview = generate_combined_api_markdown(&ctx.workspace_root, &groups)?;
            let docs_dir = ctx.workspace_root.join("docs").join("api");
            let overview_path = docs_dir.join("README.md");
            std::fs::write(&overview_path, &overview)?;
            total_files += 1;
        }

        Ok(GenerationResult {
            name: "readme",
            success: true,
            files_generated: total_files,
            output_dir: Some(
                ctx.workspace_root
                    .join("docs")
                    .join("api")
                    .to_string_lossy()
                    .to_string(),
            ),
            message: Some(format!("{} API markdown files generated", total_files)),
        })
    }
}

/// Public function matching the dao-contracts `generate_api_markdown` signature.
///
/// Generates a comprehensive API markdown file for all contracts in the workspace.
pub fn generate_api_markdown(
    workspace_root: &Path,
    groups: &[(String, BTreeMap<String, serde_json::Value>)],
) -> anyhow::Result<String> {
    let mut output = String::new();

    output.push_str("# API Reference\n\n");
    output.push_str(&format!(
        "> Auto-generated by gen-tools from workspace: {}\n\n",
        workspace_root.display()
    ));

    for (contract_name, schemas) in groups {
        if schemas.is_empty() {
            continue;
        }

        output.push_str(&format!("## {}\n\n", contract_name));
        output.push_str("### Messages\n\n");

        for (type_name, schema) in schemas {
            if type_name.contains("InstantiateMsg")
                || type_name.contains("ExecuteMsg")
                || type_name.contains("QueryMsg")
                || type_name.contains("MigrateMsg")
            {
                let title = schema
                    .get("title")
                    .and_then(|v| v.as_str())
                    .unwrap_or(type_name);
                let desc = schema
                    .get("description")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");

                output.push_str(&format!("#### `{}`\n\n", title));
                if !desc.is_empty() {
                    output.push_str(&format!("{}\n\n", desc));
                }
                output.push_str("```json\n");
                output.push_str(&serde_json::to_string_pretty(schema)?);
                output.push_str("\n```\n\n");
            }
        }
    }

    Ok(output)
}

/// Generate per-contract API markdown.
fn generate_contract_readme(
    schemas: &BTreeMap<String, serde_json::Value>,
    contract_name: &str,
) -> anyhow::Result<String> {
    let mut output = String::new();

    output.push_str(&format!("# {} API\n\n", contract_name));
    output.push_str("> Auto-generated from CosmWasm schema\n\n");

    // Contract info
    if let Some(info) = schemas.get("contract_info").or_else(|| schemas.get("ContractInfo")) {
        output.push_str("## Contract Info\n\n");
        output.push_str(&format!(
            "```json\n{}\n```\n\n",
            serde_json::to_string_pretty(info)?
        ));
    }

    // Instantiate
    if let Some(msg) = schemas
        .keys()
        .find(|k| k.contains("InstantiateMsg"))
        .and_then(|k| schemas.get(k))
    {
        output.push_str("## Instantiate\n\n");
        let desc = msg
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if !desc.is_empty() {
            output.push_str(&format!("{}\n\n", desc));
        }
        output.push_str("```json\n");
        output.push_str(&serde_json::to_string_pretty(msg)?);
        output.push_str("\n```\n\n");
        output.push_str(&generate_fields_table(msg));
    }

    // Execute
    if let Some(msg) = schemas
        .keys()
        .find(|k| k.contains("ExecuteMsg"))
        .and_then(|k| schemas.get(k))
    {
        output.push_str("## Execute Messages\n\n");

        if let Some(oneof) = msg.get("oneOf").and_then(|v| v.as_array()) {
            for variant in oneof {
                let title = variant
                    .get("title")
                    .and_then(|v| v.as_str())
                    .unwrap_or("(variant)");
                output.push_str(&format!("### `{}`\n\n", pascal_case(title)));
                if let Some(props) = variant.get("properties").and_then(|v| v.as_object()) {
                    output.push_str("| Field | Type | Description |\n");
                    output.push_str("|-------|------|-------------|\n");
                    for (name, field_schema) in props {
                        let ft = json_schema_type_to_markdown(field_schema);
                        let desc = field_schema
                            .get("description")
                            .and_then(|v| v.as_str())
                            .unwrap_or("");
                        output.push_str(&format!("| `{}` | `{}` | {} |\n", name, ft, desc));
                    }
                    output.push('\n');
                }
            }
        } else {
            output.push_str("```json\n");
            output.push_str(&serde_json::to_string_pretty(msg)?);
            output.push_str("\n```\n\n");
        }
    }

    // Queries
    if let Some(msg) = schemas
        .keys()
        .find(|k| k.contains("QueryMsg"))
        .and_then(|k| schemas.get(k))
    {
        output.push_str("## Queries\n\n");

        if let Some(oneof) = msg.get("oneOf").and_then(|v| v.as_array()) {
            for variant in oneof {
                let title = variant
                    .get("title")
                    .and_then(|v| v.as_str())
                    .unwrap_or("(variant)");
                output.push_str(&format!("### `{}`\n\n", pascal_case(title)));
                if let Some(props) = variant.get("properties").and_then(|v| v.as_object()) {
                    output.push_str("| Field | Type | Description |\n");
                    output.push_str("|-------|------|-------------|\n");
                    for (name, field_schema) in props {
                        let ft = json_schema_type_to_markdown(field_schema);
                        let desc = field_schema
                            .get("description")
                            .and_then(|v| v.as_str())
                            .unwrap_or("");
                        output.push_str(&format!("| `{}` | `{}` | {} |\n", name, ft, desc));
                    }
                    output.push('\n');
                }

                // Query response type
                let response_key = title
                    .replace("QueryMsg", "QueryResponse")
                    .replace("Query", "QueryResponse");
                if let Some(resp) = schemas.get(&response_key) {
                    output.push_str("#### Response\n\n");
                    let desc = resp
                        .get("description")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    if !desc.is_empty() {
                        output.push_str(&format!("{}\n\n", desc));
                    }
                    output.push_str("```json\n");
                    output.push_str(&serde_json::to_string_pretty(resp)?);
                    output.push_str("\n```\n\n");
                }
            }
        }
    }

    // Types index
    output.push_str("## Types\n\n");
    for (type_name, _) in schemas {
        if !type_name.contains("Msg") && !type_name.contains("Response") {
            output.push_str(&format!("- `{}`\n", type_name));
        }
    }
    output.push('\n');

    Ok(output)
}

/// Generate an overview README for all contract APIs in the workspace.
fn generate_combined_api_markdown(
    workspace_root: &Path,
    groups: &[(String, BTreeMap<String, serde_json::Value>)],
) -> anyhow::Result<String> {
    let mut output = String::new();
    output.push_str("# Contract API Reference\n\n");
    output.push_str(&format!("Workspace: `{}`\n\n", workspace_root.display()));
    output.push_str("## Available Contracts\n\n");

    for (contract_name, schemas) in groups {
        let type_count = schemas.len();
        output.push_str(&format!(
            "- **[{}]({}.api.md)** — {} schema types defined\n",
            contract_name, contract_name, type_count
        ));
    }

    output.push_str("\n---\n");
    output.push_str("_Generated by gen-tools_\n");

    Ok(output)
}

fn json_schema_type_to_markdown(schema: &serde_json::Value) -> String {
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
        return format!("[{}](#{})", pascal_case(ref_name), ref_name.to_lowercase());
    }
    if schema.get("oneOf").or_else(|| schema.get("anyOf")).is_some() {
        return "union".to_string();
    }
    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => {
            if schema.get("enum").is_some() {
                "enum"
            } else {
                "string"
            }
        }
        Some("integer") => "uint64",
        Some("boolean") => "bool",
        Some("array") => {
            if let Some(items) = schema.get("items") {
                let inner = json_schema_type_to_markdown(items);
                return format!("{}[]", inner);
            }
            "array"
        }
        _ => "unknown",
    }
    .to_string()
}

fn generate_fields_table(schema: &serde_json::Value) -> String {
    let mut output = String::new();
    if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
        let required = schema
            .get("required")
            .and_then(|v| v.as_array())
            .map(|arr| arr.iter().filter_map(|r| r.as_str()).collect::<Vec<_>>())
            .unwrap_or_default();

        output.push_str("### Fields\n\n");
        output.push_str("| Field | Type | Required | Description |\n");
        output.push_str("|-------|------|----------|-------------|\n");
        for (name, field_schema) in props {
            let ft = json_schema_type_to_markdown(field_schema);
            let req = if required.contains(&name.as_str()) {
                "Yes"
            } else {
                "No"
            };
            let desc = field_schema
                .get("description")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            output.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                name, ft, req, desc
            ));
        }
        output.push('\n');
    }
    output
}

fn pascal_case(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}