//! Rust crate generation from CosmWasm merged schemas.
//!
//! Mirrors the proto library pattern in `crates/terp-rs/proto/`:
//! - Each project gets subfolders under `src/gen/` with per-contract `.rs` files
//! - `src/lib.rs` uses `include!("gen/{project}/{contract}.rs")` to re-export
//! - Single Cargo.toml unifies all projects into one `terp-contract-types` crate

use crate::config::GenerationContext;
use crate::resolver::SourceResolver;
use crate::{GenerationResult, Generator};
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

pub struct RustGenGenerator;

impl Generator for RustGenGenerator {
    fn name(&self) -> &'static str {
        "rust"
    }

    fn enabled_by_default(&self) -> bool {
        true
    }

    fn generate(&self, ctx: &GenerationContext) -> anyhow::Result<GenerationResult> {
        let rust_out = &ctx.rust_out;
        std::fs::create_dir_all(rust_out)?;
        let src_dir = rust_out.join("src");
        std::fs::create_dir_all(&src_dir)?;
        let gen_dir = src_dir.join("gen");
        std::fs::create_dir_all(&gen_dir)?;

        let (_label, groups) = SourceResolver::resolve_grouped(ctx);
        if groups.is_empty() {
            log::warn!("[rust] No schema directories found");
            return Ok(GenerationResult {
                name: "rust",
                success: true,
                files_generated: 0,
                output_dir: Some(rust_out.to_string_lossy().to_string()),
                message: Some("No schema dirs found, skipping".into()),
            });
        }

        let mut total_files = 0;

        // Project namespace — mirrors proto's nested module hierarchy
        let project_slug = ctx.project_name.replace('-', "_");
        let project_gen_dir = gen_dir.join(&project_slug);
        std::fs::create_dir_all(&project_gen_dir)?;

        // Generate per-contract .rs files
        let mut contract_modules: Vec<String> = Vec::new();

        for (contract_name, schemas) in &groups {
            let safe_name = contract_name.replace('-', "_");
            let mut has_types = false;
            let mut struct_code = String::new();

            struct_code.push_str(&format!(
                "//! Generated CosmWasm types for `{contract_name}`.\n\
                 //! Code generated by gen-tools -- DO NOT EDIT.\n\n\
                 use cosmwasm_std::Binary;\n\
                 use schemars::JsonSchema;\n\
                 use serde::{{Deserialize, Serialize}};\n\n"
            ));

            let mut emitted: HashSet<String> = HashSet::new();

            for (_stem, merged) in schemas {
                // Extract message types (instantiate, execute, query, migrate, sudo)
                let msg_keys = ["instantiate", "execute", "query", "migrate", "sudo"];
                for key in &msg_keys {
                    if let Some(msg_val) = merged.get(*key) {
                        if msg_val.is_null() {
                            continue;
                        }
                        if let Some(title) = msg_val.get("title").and_then(|v| v.as_str()) {
                            let pascal = to_pascal_case(title);
                            if !pascal.is_empty() && emitted.insert(pascal.clone()) {
                                let s = schema_to_struct(&pascal, msg_val, "", &HashMap::new());
                                if !s.is_empty() {
                                    struct_code.push_str(&format!("// {key}\n{s}\n\n"));
                                    has_types = true;
                                }
                            }
                        }
                    }
                }

                // Response types (query responses)
                if let Some(responses) = merged.get("responses").and_then(|v| v.as_object()) {
                    for (qname, resp_schema) in responses {
                        let title = resp_schema
                            .get("title")
                            .and_then(|v| v.as_str())
                            .unwrap_or(qname);
                        let pascal = to_pascal_case(title);
                        if !pascal.is_empty() && emitted.insert(pascal.clone()) {
                            let s = schema_to_struct(&pascal, resp_schema, "", &HashMap::new());
                            if !s.is_empty() {
                                struct_code.push_str(&format!("// response {qname}\n{s}\n\n"));
                                has_types = true;
                            }
                        }
                    }
                }

                // Definitions — only emit if this schema has message types
                if has_types {
                    if let Some(defs) = merged.get("definitions").and_then(|v| v.as_object()) {
                        for (def_name, def_schema) in defs {
                            let pascal = to_pascal_case(def_name);
                            if emitted.insert(pascal.clone()) {
                                let s = schema_to_struct(&pascal, def_schema, "", &HashMap::new());
                                if !s.is_empty() {
                                    struct_code.push_str(&format!("{s}\n\n"));
                                }
                            }
                        }
                    }
                }
            }

            // Only write the contract file if it has actual types
            if has_types {
                let contract_file = project_gen_dir.join(format!("{safe_name}.rs"));
                std::fs::write(&contract_file, &struct_code)?;
                total_files += 1;
                contract_modules.push(safe_name);
            }
        }

        // Update lib.rs with include directives (proto-style nested modules)
        let lib_rs_path = src_dir.join("lib.rs");
        let mut lib_rs = if lib_rs_path.exists() {
            std::fs::read_to_string(&lib_rs_path)?
        } else {
            String::new()
        };

        if lib_rs.is_empty() {
            lib_rs.push_str(
                "//! Generated CosmWasm contract types for all Terp Network projects.\n\
                 //! Code generated by gen-tools -- DO NOT EDIT.\n\n\
                 #![allow(\n\
                     clippy::all,\n\
                     rustdoc::broken_intra_doc_links,\n\
                     non_camel_case_types,\n\
                     unused_imports\n\
                 )]\n\n\
                 // ---------------------------------------------------------------------------\n\
                 // Generated contract modules — one submodule per project, per contract\n\
                 // ---------------------------------------------------------------------------\n\n",
            );
        }

        if !contract_modules.is_empty() {
            lib_rs.push_str(&format!("pub mod {project_slug} {{\n"));

            for mod_name in &contract_modules {
                lib_rs.push_str(&format!("    pub mod {mod_name} {{\n"));
                lib_rs.push_str(&format!(
                    "        include!(\"gen/{project_slug}/{mod_name}.rs\");\n"
                ));
                lib_rs.push_str("    }\n");
            }

            lib_rs.push_str("}\n\n");
        }

        // Write files
        std::fs::write(&lib_rs_path, &lib_rs)?;
        total_files += 1;

        let cargo_path = rust_out.join("Cargo.toml");
        if !cargo_path.exists() {
            std::fs::write(
                &cargo_path,
                "[package]\n\
                 name = \"terp-contract-types\"\n\
                 version = \"0.1.0\"\n\
                 edition = \"2021\"\n\
                 description = \"Generated Rust types for all CosmWasm contracts (Terp Network)\"\n\
                 \n\
                 [dependencies]\n\
                 cosmwasm-std = { workspace = true }\n\
                 schemars = \"0.8\"\n\
                 serde = { version = \"1\", features = [\"derive\"] }\n\
                 serde_json = \"1\"\n",
            )?;
            total_files += 1;
        }

        let toolchain_path = rust_out.join("rust-toolchain.toml");
        if !toolchain_path.exists() {
            std::fs::write(&toolchain_path, "[toolchain]\nchannel = \"1.75.0\"\n")?;
            total_files += 1;
        }

        log::info!(
            "[rust] Project '{}': {} contract(s), {} file(s)",
            project_slug,
            contract_modules.len(),
            total_files
        );

        Ok(GenerationResult {
            name: "rust",
            success: true,
            files_generated: total_files,
            output_dir: Some(rust_out.to_string_lossy().to_string()),
            message: Some(format!(
                "{} contract module(s) for project '{}' ({} files)",
                contract_modules.len(),
                project_slug,
                total_files
            )),
        })
    }
}

// ---------------------------------------------------------------------------
// Schema → Rust struct helpers
// ---------------------------------------------------------------------------

fn schema_to_struct(
    name: &str,
    schema: &serde_json::Value,
    _indent: &str,
    _defs: &HashMap<String, serde_json::Value>,
) -> String {
    // oneOf -> enum (with #[serde(untagged)])
    if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
        if variants.is_empty() {
            return String::new();
        }
        let mut out = String::new();
        out.push_str("#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n");
        out.push_str("#[serde(untagged)]\n");
        out.push_str(&format!("pub enum {name} {{\n"));

        let mut vidx = 0usize;
        for variant in variants {
            vidx += 1;
            if let Some(vtype) = variant.get("type").and_then(|v| v.as_str()) {
                match vtype {
                    "object" => {
                        if let Some(props) = variant.get("properties").and_then(|v| v.as_object())
                        {
                            let required: HashSet<&str> = variant
                                .get("required")
                                .and_then(|v| v.as_array())
                                .map(|a| a.iter().filter_map(|r| r.as_str()).collect())
                                .unwrap_or_default();

                            let fields: Vec<String> = props
                                .iter()
                                .map(|(fn_, fs)| {
                                    let ty = json_type_to_rust(fs);
                                    format!(
                                        "    pub {fn_}: {},",
                                        if required.contains(fn_.as_str()) {
                                            ty
                                        } else {
                                            format!("Option<{ty}>")
                                        }
                                    )
                                })
                                .collect();

                            if fields.is_empty() {
                                out.push_str(&format!("    V{vidx}(::cosmwasm_std::Empty),\n"));
                            } else {
                                out.push_str(&format!("    V{vidx}{{\n{}\n    }},\n", fields.join("\n")));
                            }
                        } else {
                            out.push_str(&format!("    V{vidx}(::cosmwasm_std::Empty),\n"));
                        }
                    }
                    _ => {
                        let ty = json_type_to_rust(variant);
                        out.push_str(&format!("    V{vidx}({ty}),\n"));
                    }
                }
            } else if variant.get("$ref").is_some() {
                out.push_str(&format!("    V{vidx}(::cosmwasm_std::Binary),\n"));
            } else {
                out.push_str(&format!("    V{vidx}(::cosmwasm_std::Empty),\n"));
            }
        }

        out.push_str("}\n");
        return out;
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("object") => {
            let props = match schema.get("properties").and_then(|v| v.as_object()) {
                Some(p) => p,
                None => {
                    return format!(
                        "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                         pub struct {name} {{}}\n"
                    );
                }
            };

            let required: HashSet<&str> = schema
                .get("required")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|r| r.as_str()).collect())
                .unwrap_or_default();

            let mut out = String::new();
            out.push_str("#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n");
            out.push_str(&format!("pub struct {name} {{\n"));

            for (fn_, fs) in props {
                let ty = json_type_to_rust(fs);
                out.push_str(&format!(
                    "    pub {fn_}: {},\n",
                    if required.contains(fn_.as_str()) {
                        ty
                    } else {
                        format!("Option<{ty}>")
                    }
                ));
            }

            out.push_str("}\n");
            out
        }
        Some("string") => {
            if let Some(enum_vals) = schema.get("enum").and_then(|v| v.as_array()) {
                if enum_vals.len() <= 1 {
                    return format!(
                        "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                         pub struct {name}(pub String);\n"
                    );
                }
                let mut out = String::new();
                out.push_str("#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n");
                out.push_str(&format!("pub enum {name} {{\n"));
                for val in enum_vals {
                    if let Some(s) = val.as_str() {
                        out.push_str(&format!("    {},\n", to_pascal_case(s)));
                    }
                }
                out.push_str("}\n");
                out
            } else {
                format!(
                    "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                     pub struct {name}(pub String);\n"
                )
            }
        }
        Some("integer") | Some("number") => {
            format!(
                "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                 pub struct {name}(pub u64);\n"
            )
        }
        Some("boolean") => {
            format!(
                "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                 pub struct {name}(pub bool);\n"
            )
        }
        Some("array") => {
            let inner = schema
                .get("items")
                .map(|i| json_type_to_rust(i))
                .unwrap_or_else(|| "String".into());
            format!(
                "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                 pub struct {name}(pub Vec<{inner}>);\n"
            )
        }
        _ => {
            format!(
                "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]\n\
                 pub struct {name}(pub ::cosmwasm_std::Binary);\n"
            )
        }
    }
}

fn json_type_to_rust(schema: &serde_json::Value) -> String {
    if let Some(ref_str) = schema.get("$ref").and_then(|v| v.as_str()) {
        let name = ref_str
            .trim_start_matches("#/definitions/")
            .trim_start_matches("#/components/schemas/")
            .trim_start_matches("definitions/");
        return to_pascal_case(name);
    }

    if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
        if variants.is_empty() {
            return "::cosmwasm_std::Empty".to_string();
        }
        let first_type = variants[0].get("type").and_then(|v| v.as_str());
        if variants.len() == 1 && first_type == Some("string") {
            return "String".to_string();
        }
        return "::cosmwasm_std::Binary".to_string();
    }

    if let Some(type_str) = schema.get("type").and_then(|v| v.as_str()) {
        match type_str {
            "string" => {
                if let Some(fmt) = schema.get("format").and_then(|v| v.as_str()) {
                    match fmt {
                        "byte" | "binary" => return "::cosmwasm_std::Binary".to_string(),
                        "date-time" | "date" | "time" => return "String".to_string(),
                        "uint" => return "::cosmwasm_std::Uint128".to_string(),
                        "int" => return "::cosmwasm_std::Int256".to_string(),
                        "decimal" => return "::cosmwasm_std::Decimal".to_string(),
                        _ => {}
                    }
                }
                if let Some(desc) = schema.get("description").and_then(|v| v.as_str()) {
                    let lower = desc.to_lowercase();
                    if lower.contains("addr") {
                        return "String".to_string();
                    }
                    if lower.contains("uint128") {
                        return "::cosmwasm_std::Uint128".to_string();
                    }
                    if lower.contains("decimal") {
                        return "::cosmwasm_std::Decimal".to_string();
                    }
                }
                "String".to_string()
            }
            "integer" => "u64".to_string(),
            "number" => "u128".to_string(),
            "boolean" => "bool".to_string(),
            "array" => {
                let inner = schema
                    .get("items")
                    .map(|i| json_type_to_rust(i))
                    .unwrap_or_else(|| "String".to_string());
                format!("Vec<{inner}>")
            }
            "object" => "::serde_json::Value".to_string(),
            _ => "String".to_string(),
        }
    } else {
        "String".to_string()
    }
}

fn to_pascal_case(s: &str) -> String {
    let s = s.replace(|c: char| c == '-' || c == '_' || c == '.', " ");
    let mut result = String::with_capacity(s.len());
    let mut capitalize = true;
    for ch in s.chars() {
        if ch == ' ' {
            capitalize = true;
        } else if capitalize {
            result.push(ch.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(ch);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("instantiate"), "Instantiate");
        assert_eq!(to_pascal_case("execute_msg"), "ExecuteMsg");
        assert_eq!(to_pascal_case("my-contract"), "MyContract");
        assert_eq!(to_pascal_case("query_msg"), "QueryMsg");
    }

    #[test]
    fn test_json_type_string() {
        let schema = serde_json::json!({"type": "string"});
        assert_eq!(json_type_to_rust(&schema), "String");
    }

    #[test]
    fn test_json_type_uint128() {
        let schema = serde_json::json!({"type": "string", "format": "uint"});
        assert_eq!(json_type_to_rust(&schema), "::cosmwasm_std::Uint128");
    }

    #[test]
    fn test_json_type_binary() {
        let schema = serde_json::json!({"type": "string", "format": "binary"});
        assert_eq!(json_type_to_rust(&schema), "::cosmwasm_std::Binary");
    }

    #[test]
    fn test_json_type_ref() {
        let schema = serde_json::json!({"$ref": "#/definitions/Uint128"});
        assert_eq!(json_type_to_rust(&schema), "Uint128");
    }

    #[test]
    fn test_schema_to_struct_object() {
        let schema = serde_json::json!({
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "amount": {"type": "string", "format": "uint"}
            },
            "required": ["name"]
        });
        let result = schema_to_struct("InstantiateMsg", &schema, "", &HashMap::new());
        assert!(result.contains("pub struct InstantiateMsg"));
        assert!(result.contains("pub name: String,"));
        assert!(result.contains("pub amount: Option<::cosmwasm_std::Uint128>,"));
    }

    #[test]
    fn test_schema_to_struct_oneof_enum() {
        let schema = serde_json::json!({
            "oneOf": [
                {"type": "object", "properties": {"transfer": {"type": "string"}}},
                {"type": "object", "properties": {"burn": {"type": "string"}}}
            ]
        });
        let result = schema_to_struct("ExecuteMsg", &schema, "", &HashMap::new());
        assert!(result.contains("pub enum ExecuteMsg"));
        assert!(result.contains("#[serde(untagged)]"));
    }
}