//! Zod schema generation from CosmWasm merged schemas.
//!
//! Generates TypeScript Zod validation schemas from CosmWasm merged schema
//! JSON. Extracts message types (instantiate, execute, query, migrate, sudo),
//! response types, and definitions, then generates z.object(), z.union(),
//! z.enum(), z.array() and primitive schemas accordingly.

use crate::config::GenerationContext;
use crate::resolver::SourceResolver;
use crate::{GenerationResult, Generator};
use std::collections::{BTreeMap, HashMap, HashSet};

pub struct ZodGenGenerator;

impl Generator for ZodGenGenerator {
    fn name(&self) -> &'static str { "zod" }
    fn enabled_by_default(&self) -> bool { true }

    fn generate(&self, ctx: &GenerationContext) -> anyhow::Result<GenerationResult> {
        let zod_out = ctx.zod_out.join(&ctx.project_name);
        std::fs::create_dir_all(&zod_out)?;
        let mut total_files = 0;
        let (_label, groups) = SourceResolver::resolve_grouped(ctx);
        if groups.is_empty() {
            log::warn!("[zod] No type sources found");
            return Ok(GenerationResult { name: "zod", success: true, files_generated: 0, output_dir: Some(zod_out.to_string_lossy().to_string()), message: Some("No type sources found, skipping".into()) });
        }
        for (contract_name, schemas) in &groups {
            let ts_name = contract_name.replace('.', "-");
            let zod_content = generate_zod_file(schemas, contract_name)?;
            let zod_path = zod_out.join(format!("{}.ts", ts_name));
            std::fs::write(&zod_path, &zod_content)?;
            total_files += 1;
            log::info!("[zod] Wrote {:?}", zod_path);
        }
        if total_files > 0 {
            let mut barrel = String::new();
            barrel.push_str("// Auto-generated barrel export — do not edit.\n// Run `gen-tools --steps zod` to regenerate.\n\n");
            for (contract_name, _) in &groups {
                let ts_name = contract_name.replace('.', "-");
                barrel.push_str(&format!("export * from './{}.js';\n", ts_name));
            }
            std::fs::write(zod_out.join("index.ts"), &barrel)?;
            total_files += 1;
        }
        Ok(GenerationResult { name: "zod", success: true, files_generated: total_files, output_dir: Some(zod_out.to_string_lossy().to_string()), message: Some(format!("{} Zod schema files generated", total_files)) })
    }
}

fn generate_zod_file(schemas: &BTreeMap<String, serde_json::Value>, contract_name: &str) -> anyhow::Result<String> {
    let mut output = String::new();
    output.push_str(&format!("// Auto-generated by gen-tools from {contract_name} schema\n// Do not edit manually.\n\nimport {{ z }} from 'zod';\nimport type {{ HexBinary }} from './types';\n\n"));

    // Skip metadata keys
    let skip_keys: HashSet<&str> = ["contract_name", "contract_version", "idl_version", "$schema", "_schema_version"].into();

    // Extract message types (instantiate, execute, query, migrate, sudo)
    let msg_keys = ["instantiate", "execute", "query", "migrate", "sudo"];
    let mut all_defs: HashMap<String, serde_json::Value> = HashMap::new();
    let mut message_types: Vec<(String, serde_json::Value)> = Vec::new();
    let mut response_types: Vec<(String, serde_json::Value)> = Vec::new();

    for (_key, merged) in schemas {
        // Iterate inner keys of the merged schema JSON object
        let inner_obj = match merged.as_object() {
            Some(obj) => obj,
            None => continue,
        };
        for (inner_key, inner_val) in inner_obj {
            if skip_keys.contains(inner_key.as_str()) { continue; }
            if msg_keys.contains(&inner_key.as_str()) {
                if !inner_val.is_null() {
                    let title = inner_val.get("title").and_then(|v| v.as_str()).unwrap_or(inner_key).to_string();
                    message_types.push((title, inner_val.clone()));
                    if let Some(defs) = inner_val.get("definitions").and_then(|v| v.as_object()) {
                        for (dk, dv) in defs {
                            all_defs.entry(dk.clone()).or_insert_with(|| dv.clone());
                        }
                    }
                }
            } else if inner_key == "responses" {
                if let Some(responses) = inner_val.as_object() {
                    for (qname, resp_schema) in responses {
                        let title = resp_schema.get("title").and_then(|v| v.as_str()).unwrap_or(qname).to_string();
                        response_types.push((title, resp_schema.clone()));
                        if let Some(defs) = resp_schema.get("definitions").and_then(|v| v.as_object()) {
                            for (dk, dv) in defs {
                                all_defs.entry(dk.clone()).or_insert_with(|| dv.clone());
                            }
                        }
                    }
                }
            }
        }
    }

    // Generate definitions first
    let def_names: Vec<String> = all_defs.keys().cloned().collect();
    for name in &def_names {
        if let Some(schema) = all_defs.get(name) {
            let zod_schema = json_type_to_zod(schema, &all_defs);
            let clean = pascal_case(name);
            output.push_str(&format!("export const {}Schema = {};\n", clean, zod_schema));
            output.push_str(&format!("export type {} = z.infer<typeof {}Schema>;\n\n", clean, clean));
        }
    }

    // Generate message types (exec, query, etc.) as discriminated unions
    for (title, schema) in &message_types {
        let clean = pascal_case(title);
        // oneOf -> discriminatedUnion
        if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
            let var_types: Vec<String> = variants.iter().map(|v| {
                if let Some(ref_path) = v.get("$ref").and_then(|v| v.as_str()) {
                    let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
                    let clean_ref = pascal_case(ref_name);
                    format!("{}Schema", clean_ref)
                } else if let Some(_props) = v.get("properties").and_then(|v| v.as_object()) {
                    // Inline variant — generate inline
                    inline_variant_to_zod(v, &all_defs)
                } else {
                    "z.object({})".to_string()
                }
            }).collect();
            // Try discriminatedUnion if there's a common discriminator field
            // Otherwise fall back to z.union
            let union_type = if let Some(var0) = variants.first() {
                if let Some(ref_path) = var0.get("$ref").and_then(|v| v.as_str()) {
                    let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
                    format!("z.union([{}])", var_types.join(", "))
                } else {
                    format!("z.union([{}])", var_types.join(", "))
                }
            } else {
                format!("z.union([{}])", var_types.join(", "))
            };
            output.push_str(&format!("export const {}Schema = {};\n", clean, union_type));
            output.push_str(&format!("export type {} = z.infer<typeof {}Schema>;\n\n", clean, clean));
        } else {
            // Single object type
            let zod_schema = json_type_to_zod(schema, &all_defs);
            output.push_str(&format!("export const {}Schema = {};\n", clean, zod_schema));
            output.push_str(&format!("export type {} = z.infer<typeof {}Schema>;\n\n", clean, clean));
        }
    }

    // Generate response types
    for (title, schema) in &response_types {
        let clean = pascal_case(&title);
        let zod_schema = json_type_to_zod(schema, &all_defs);
        output.push_str(&format!("export const {}ResponseSchema = {};\n", clean, zod_schema));
        output.push_str(&format!("export type {}Response = z.infer<typeof {}ResponseSchema>;\n\n", clean, clean));
    }

    // Package metadata export
    output.push_str(&format!("export const PACKAGE = '{}' as const;\n\n", contract_name));
    Ok(output)
}

fn inline_variant_to_zod(schema: &serde_json::Value, all_defs: &HashMap<String, serde_json::Value>) -> String {
    if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
        let required: Vec<&str> = schema.get("required").and_then(|v| v.as_array()).map(|arr| arr.iter().filter_map(|r| r.as_str()).collect()).unwrap_or_default();
        let fields: Vec<String> = props.iter().map(|(k, v)| {
            let zv = json_type_to_zod(v, all_defs);
            let opt = if required.contains(&k.as_str()) { "" } else { ".optional()" };
            format!("  {}: {}{}", k, zv, opt)
        }).collect();
        format!("z.object({{\n{}\n}})", fields.join(",\n"))
    } else {
        "z.object({})".to_string()
    }
}

fn json_type_to_zod(schema: &serde_json::Value, all_defs: &HashMap<String, serde_json::Value>) -> String {
    // 1) Unwrap allOf wrapping — single-$ref allOf: [{$ref: "..."}]
    if let Some(allof) = schema.get("allOf").and_then(|v| v.as_array()) {
        if allof.len() == 1 {
            if let Some(ref_path) = allof[0].get("$ref").and_then(|v| v.as_str()) {
                let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
                let clean = pascal_case(ref_name);
                return format!("z.lazy(() => {}Schema)", clean);
            }
        }
    }

    // 2) Unwrap anyOf with null (nullable pattern)
    if let Some(anyof) = schema.get("anyOf").and_then(|v| v.as_array()) {
        let non_null: Vec<&serde_json::Value> = anyof.iter()
            .filter(|v| v.get("type").and_then(|t| t.as_str()) != Some("null"))
            .collect();
        if non_null.len() == 1 {
            return json_type_to_zod(non_null[0], all_defs);
        }
    }

    // 3) Handle type as array (["integer", "null"] for optional ints)
    if let Some(types) = schema.get("type").and_then(|v| v.as_array()) {
        for t in types {
            if let Some(type_str) = t.as_str() {
                if type_str != "null" {
                    let single = serde_json::json!({"type": type_str});
                    return json_type_to_zod(&single, all_defs);
                }
            }
        }
    }

    // 4) $ref
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        let ref_name = ref_path.rsplit('/').next().unwrap_or(ref_path);
        let clean = pascal_case(ref_name);
        return format!("z.lazy(() => {}Schema)", clean);
    }

    // oneOf/anyOf
    if let Some(variants) = schema.get("oneOf").or_else(|| schema.get("anyOf")).and_then(|v| v.as_array()) {
        let types: Vec<String> = variants.iter().map(|v| json_type_to_zod(v, all_defs)).collect();
        return format!("z.union([{}])", types.join(", "));
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => {
            if let Some(variants) = schema.get("enum").and_then(|v| v.as_array()) {
                let vals: Vec<String> = variants.iter().filter_map(|v| v.as_str()).map(|v| format!("'{}'", v)).collect();
                return format!("z.enum([{}])", vals.join(", "));
            }
            match schema.get("format").and_then(|v| v.as_str()) {
                Some("uint64" | "int64") => "z.string()".to_string(),
                Some("date-time") => "z.string().datetime()".to_string(),
                _ => "z.string()".to_string(),
            }
        }
        Some("integer") => "z.number().int()".to_string(),
        Some("number") => "z.number()".to_string(),
        Some("boolean") => "z.boolean()".to_string(),
        Some("array") => {
            if let Some(items) = schema.get("items") {
                let inner = json_type_to_zod(items, all_defs);
                format!("z.array({})", inner)
            } else {
                "z.array(z.unknown())".to_string()
            }
        }
        _ => {
            // Inline object
            if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
                inline_variant_to_zod(schema, all_defs)
            } else {
                "z.unknown()".to_string()
            }
        }
    }
}

fn pascal_case(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric()).filter(|w| !w.is_empty()).map(|w| {
        let mut c = w.chars();
        match c.next() {
            None => String::new(),
            Some(f) => f.to_uppercase().to_string() + c.as_str(),
        }
    }).collect()
}
