flowchart TB
    bridge_execute_bridge_mint_note["execute_bridge_mint_note function CC=2"]
    proxy_unresolved_BRIDGE_CFG__may_load_deps_storage___ok_or["BRIDGE_CFG .may_load deps.storage .ok_or proxy"]
    proxy_unresolved_REFLECTION_SNAPSHOT__may_load_deps_storage___ok_or["REFLECTION_SNAPSHOT .may_load deps.storage .ok_or proxy"]
    proxy_unresolved_REFLECTION_SNAPSHOT__may_load["REFLECTION_SNAPSHOT .may_load proxy"]
    bridge_require_hash32["require_hash32 function CC=2"]
    bridge_bridge_claim_storage_key["bridge_claim_storage_key function CC=1"]
    proxy_unresolved_BRIDGE_MINTED_may_load_deps_storage___mint_key__is_some["BRIDGE_MINTED.may_load deps.storage mint_key .is_some proxy"]
    bridge_terp_asset_id_from_tacit["terp_asset_id_from_tacit function CC=1"]
    bridge_asset_id_key["asset_id_key function CC=1"]
    proxy_unresolved_asset_is_none["asset.is_none proxy"]
    bridge_authorize_bridge_mint_pure["authorize_bridge_mint_pure function CC=23"]
    proxy_unresolved_asset_as_ref["asset.as_ref proxy"]
    bridge_mock_verify_bridge_proof["mock_verify_bridge_proof function CC=4"]
    proxy_unresolved_BRIDGE_MINTED_save["BRIDGE_MINTED.save proxy"]
    proxy_unresolved_crate__NULLIFIERS_save["crate::NULLIFIERS.save proxy"]
    proxy_unresolved_mint_key_clone["mint_key.clone proxy"]
    proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute_nullifier__hex__encode_nu___add_attribute_claim_key__mint_key___add_attribute["Response::new .add_attribute action bridge_mint_note .add_attribute n..."]
    proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute["Response::new .add_attribute action bridge_mint_note .add_attribute p..."]
    proxy_unresolved_Response__new___add_attribute["Response::new .add_attribute proxy"]
    proxy_unresolved_hex__encode["hex::encode proxy"]
    proxy_unresolved_note_is_dex_consumable__to_string["note.is_dex_consumable .to_string proxy"]
    proxy_unresolved_note_is_dex_consumable["note.is_dex_consumable proxy"]
    proxy_unresolved_note_bin_to_base64["note_bin.to_base64 proxy"]
    proxy_unresolved_b_as_slice["b.as_slice proxy"]
    proxy_unresolved_s_len["s.len proxy"]
    proxy_unresolved_StdError__msg["StdError::msg proxy"]
    proxy_unresolved_out_copy_from_slice["out.copy_from_slice proxy"]
    bridge_execute_register_asset["execute_register_asset function CC=2"]
    bridge_execute_set_bridge_cfg["execute_set_bridge_cfg function CC=1"]
    bridge_query_is_bridge_minted["query_is_bridge_minted function CC=1"]
    bridge_query_asset["query_asset function CC=1"]
    proxy_unresolved_source_chain_tag_as_bytes["source_chain_tag.as_bytes proxy"]
    proxy_unresolved_h_finalize["h.finalize proxy"]
    bridge_happy_bridge_mint_world["happy_bridge_mint_world function CC=1"]
    bridge_is_zero_hash["is_zero_hash function CC=1"]
    proxy_unresolved_require_hash32_claim_source_pool_root___source_pool_root___map_err["require_hash32 claim.source_pool_root source_pool_root .map_err proxy"]
    proxy_unresolved_require_hash32_claim_tacit_asset_id___tacit_asset_id___map_err["require_hash32 claim.tacit_asset_id tacit_asset_id .map_err proxy"]
    proxy_unresolved_require_hash32_entry_asset_id___asset_id__map_err["require_hash32 entry.asset_id asset_id .map_err proxy"]
    bridge_derive_claim_id_with_dest["derive_claim_id_with_dest function CC=1"]
    bridge_derive_domain_binding["derive_domain_binding function CC=1"]
    bridge_hash_source_chain_tag["hash_source_chain_tag function CC=1"]
    bridge_query_reflection_tip["query_reflection_tip function CC=1"]
    bridge_query_bridge_cfg["query_bridge_cfg function CC=1"]
    bridge_query_external_asset_registry["query_external_asset_registry function CC=1"]
    bridge_ensure_bridge_cfg["ensure_bridge_cfg function CC=2"]
    bridge_execute_update_reflection["execute_update_reflection function CC=3"]
    bridge_execute_set_reflection_snapshot["execute_set_reflection_snapshot function CC=1"]
    bridge_execute_set_external_asset_registry["execute_set_external_asset_registry function CC=3"]
    headstash_register_eligibility_root["register_eligibility_root function CC=1"]
    lib_instantiate["instantiate function CC=5"]
    lib_reply["reply function CC=7"]
    headstash_process_headstash["process_headstash function CC=12"]
    lib_execute_mint["execute_mint function CC=2"]
    lib_execute_burn["execute_burn function CC=2"]
    wavs_generate_test_wavs_proof["generate_test_wavs_proof function CC=2"]
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_CFG__may_load_deps_storage___ok_or
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_REFLECTION_SNAPSHOT__may_load_deps_storage___ok_or
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_REFLECTION_SNAPSHOT__may_load
    bridge_execute_bridge_mint_note --> bridge_require_hash32
    bridge_execute_bridge_mint_note --> bridge_bridge_claim_storage_key
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_MINTED_may_load_deps_storage___mint_key__is_some
    bridge_execute_bridge_mint_note --> bridge_require_hash32
    bridge_execute_bridge_mint_note --> bridge_terp_asset_id_from_tacit
    bridge_execute_bridge_mint_note --> bridge_asset_id_key
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_asset_is_none
    bridge_execute_bridge_mint_note --> bridge_asset_id_key
    bridge_execute_bridge_mint_note --> bridge_authorize_bridge_mint_pure
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_asset_as_ref
    bridge_execute_bridge_mint_note --> bridge_mock_verify_bridge_proof
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_MINTED_save
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_crate__NULLIFIERS_save
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_mint_key_clone
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute_nullifier__hex__encode_nu___add_attribute_claim_key__mint_key___add_attribute
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_hex__encode
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_is_dex_consumable__to_string
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_is_dex_consumable
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_bin_to_base64
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_CFG__may_load_deps_storage___ok_or
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_REFLECTION_SNAPSHOT__may_load_deps_storage___ok_or
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_REFLECTION_SNAPSHOT__may_load
    bridge_require_hash32 -.-> proxy_unresolved_b_as_slice
    bridge_require_hash32 -.-> proxy_unresolved_s_len
    bridge_require_hash32 -.-> proxy_unresolved_StdError__msg
    bridge_require_hash32 -.-> proxy_unresolved_out_copy_from_slice
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_execute_register_asset --> bridge_require_hash32
    bridge_execute_set_bridge_cfg --> bridge_require_hash32
    bridge_execute_bridge_mint_note --> bridge_require_hash32
    bridge_execute_bridge_mint_note --> bridge_require_hash32
    bridge_query_is_bridge_minted --> bridge_require_hash32
    bridge_query_asset --> bridge_require_hash32
    bridge_execute_bridge_mint_note --> bridge_bridge_claim_storage_key
    bridge_query_is_bridge_minted --> bridge_bridge_claim_storage_key
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_MINTED_may_load_deps_storage___mint_key__is_some
    bridge_terp_asset_id_from_tacit -.-> proxy_unresolved_source_chain_tag_as_bytes
    bridge_terp_asset_id_from_tacit -.-> proxy_unresolved_h_finalize
    bridge_terp_asset_id_from_tacit -.-> proxy_unresolved_out_copy_from_slice
    bridge_authorize_bridge_mint_pure --> bridge_terp_asset_id_from_tacit
    bridge_execute_bridge_mint_note --> bridge_terp_asset_id_from_tacit
    bridge_happy_bridge_mint_world --> bridge_terp_asset_id_from_tacit
    bridge_asset_id_key -.-> proxy_unresolved_hex__encode
    bridge_execute_register_asset --> bridge_asset_id_key
    bridge_execute_bridge_mint_note --> bridge_asset_id_key
    bridge_execute_bridge_mint_note --> bridge_asset_id_key
    bridge_query_asset --> bridge_asset_id_key
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_asset_is_none
    bridge_authorize_bridge_mint_pure --> bridge_is_zero_hash
    bridge_authorize_bridge_mint_pure --> bridge_is_zero_hash
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure -.-> proxy_unresolved_require_hash32_claim_source_pool_root___source_pool_root___map_err
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure -.-> proxy_unresolved_require_hash32_claim_tacit_asset_id___tacit_asset_id___map_err
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_terp_asset_id_from_tacit
    bridge_authorize_bridge_mint_pure -.-> proxy_unresolved_require_hash32_entry_asset_id___asset_id__map_err
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_derive_claim_id_with_dest
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_derive_domain_binding
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_is_zero_hash
    bridge_authorize_bridge_mint_pure --> bridge_require_hash32
    bridge_authorize_bridge_mint_pure --> bridge_hash_source_chain_tag
    bridge_execute_bridge_mint_note --> bridge_authorize_bridge_mint_pure
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_asset_as_ref
    bridge_mock_verify_bridge_proof -.-> proxy_unresolved_StdError__msg
    bridge_mock_verify_bridge_proof -.-> proxy_unresolved_StdError__msg
    bridge_mock_verify_bridge_proof -.-> proxy_unresolved_StdError__msg
    bridge_execute_bridge_mint_note --> bridge_mock_verify_bridge_proof
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_BRIDGE_MINTED_save
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_crate__NULLIFIERS_save
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_mint_key_clone
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute_nullifier__hex__encode_nu___add_attribute_claim_key__mint_key___add_attribute
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute_action___bridge_mint_note___add_attribute
    bridge_execute_update_reflection -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_set_reflection_snapshot -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_register_asset -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_set_external_asset_registry -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_set_bridge_cfg -.-> proxy_unresolved_Response__new___add_attribute
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_Response__new___add_attribute
    headstash_register_eligibility_root -.-> proxy_unresolved_Response__new___add_attribute
    lib_instantiate -.-> proxy_unresolved_Response__new___add_attribute
    lib_instantiate -.-> proxy_unresolved_Response__new___add_attribute
    lib_reply -.-> proxy_unresolved_Response__new___add_attribute
    bridge_asset_id_key -.-> proxy_unresolved_hex__encode
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_hex__encode
    wavs_generate_test_wavs_proof -.-> proxy_unresolved_hex__encode
    wavs_generate_test_wavs_proof -.-> proxy_unresolved_hex__encode
    wavs_generate_test_wavs_proof -.-> proxy_unresolved_hex__encode
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_is_dex_consumable__to_string
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_is_dex_consumable
    bridge_execute_bridge_mint_note -.-> proxy_unresolved_note_bin_to_base64
%% reduced from 103 nodes to 70 for render
%% pruned 70->55 nodes for mmdc
