[package]
name = "terp-auth"
description = "Types and TerpAccountTrait for x/smart-account CosmWasm authenticators"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true, features = ["std"] }
cw-utils = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = "0.23"
